### ISSUE TITLE
[ Mac ] Cannot connect to my google account .

### ISSUE THREAD

**Issue by TiagonewDEV** [ytmdesktop/ytmdesktop#527] opened 2020-12-12 16:02 UTC
- [Yes] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [No] I verified that there is no open issue for the same subject.

Cannot connect to my google account 

**To Reproduce**
1. Open the app ( Duh )
2. Click on sign in
3. Sign in to your Google account 
4. See error wich is : This browser or application may not be secure. Learn more

Try to use a different browser. If you're already using a compatible browser, you can refresh the screen and try to sign in again.

**Screenshots**
The prob is that my Mac is in french :/

**Environment (please complete the following information):**
 * YTMDesktop version: 1.13.0 (1.13.0)
 * OS:Mac
 * OS version: OSX El Capitan ( Yes im out dated ) 10.11.6
 * Arch: Like all Mac x64
* Installation way: .DMG file on the electron.js site

**Comment by Maskime** [comment] 2020-12-14 10:42
Few questions (I was faced with a similar issue):
  1. Are you behind a proxy ?
  1. Are you able to connect to youtube music with chrome ?

**Comment by TiagonewDEV** [comment] 2020-12-15 16:49
Sorry for that ... 

1 : No im not behind a proxy
2 : Yes im able to connect to YouTube Music with Chrome !

**Comment by tomasbreffitt** [comment] 2021-01-01 22:45
I am also experiencing this issue. I am not behind a proxy, I can sign in with google chrome. I am able to input my username and password fine. The next step 2 step verification. The app shows this, but I never receive the pop up on my android phone to confirm login.

**Comment by autoferrit** [comment] 2022-01-22 18:00
I am having the same issue, I am in a proxy, but only to access work stuff. I am not getting any popups. And trying to show the console it gets hidden behind the UI.
![image](https://user-images.githubusercontent.com/89895/150650179-71d8049b-1b6c-40e7-a175-28e2499dff21.png)
So I can't see the error message with it. 
I am also able to log into the website with no problems.

**Comment by Alipoodle** [comment] 2022-05-24 15:28
Duplicate of #866 (master ticket now, with a few guides on fixing)

**Closed by Alipoodle** 2022-05-24 15:28 UTC
