### ISSUE TITLE
Program Not Opening Correctly

### ISSUE THREAD

**Issue by JoshMayberry** [ytmdesktop/ytmdesktop#1007] opened 2022-07-20 20:52 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I start the program, I see it in the app bar, but the window does not appear anywhere.
![image](https://user-images.githubusercontent.com/11482252/180071867-1e7d57d9-8bcb-4b33-9d1c-0cad081a552a.png)

### Expected Behavior

When I start the program, for the GUI window to appear and be usable by me.

### Steps To Reproduce

1. Open the program
2. That's it

### YTMDesktop

latest

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

.exe

### Anything else?

It was working about 2 weeks ago, but then stopped working. I'm not sure what to do now.

### Things I've tried
- Restarting the computer does not fix it
- Uninstalling and reinstalling does not fix it.
- Changing screen resolution/messing with displays does not make it show up (Things that normally make windows that are showing up off screen move back to the main screen)- so I don't think that is the issue here.
- I removed my antivirus software, and the issue is still happening
- My windows updates are all up to date

### In case it helps, here's my computer's info
OS Name	Microsoft Windows 10 Pro
Version	10.0.19044 Build 19044
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-8J5RE8C
System Manufacturer	To Be Filled By O.E.M.
System Model	To Be Filled By O.E.M.
System Type	x64-based PC
System SKU	To Be Filled By O.E.M.
Processor	AMD Ryzen 9 5950X 16-Core Processor, 3401 Mhz, 16 Core(s), 32 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. P1.20, 8/13/2020
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	ASRock
BaseBoard Product	B550 Steel Legend
BaseBoard Version	
Platform Role	Desktop
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume2
Locale	United States
Hardware Abstraction Layer	Version = "10.0.19041.1741"
Installed Physical Memory (RAM)	64.0 GB
Total Physical Memory	63.9 GB
Available Physical Memory	55.4 GB
Total Virtual Memory	73.4 GB
Available Virtual Memory	61.9 GB
Page File Space	9.50 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Not enabled
Device Encryption Support	Reasons for failed automatic device encryption: TPM is not usable, PCR7 binding is not supported, Hardware Security Test Interface failed and device is not Modern Standby, Un-allowed DMA capable bus/device(s) detected, TPM is not usable
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by Alipoodle** [comment] 2022-07-21 18:45
Dupe of #918 
Please follow the steps but for the main windows instead of Miniplayer.

**Closed by Alipoodle** 2022-07-21 18:45 UTC

**Comment by JoshMayberry** [comment] 2022-07-21 20:13
Thank you! It was set to.
```
"window-position": {
  "x": -32000,
  "y": -32000
}
```
