### ISSUE TITLE
Window will only open up on a ghost display.

### ISSUE THREAD

**Issue by RyanHakurei** [ytmdesktop/ytmdesktop#1016] opened 2022-08-09 12:45 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The app will only maximize off screen to a ghost display, and any attempts to bring the window into view fail. It's hard to explain so I've attached 2 screenshots. This is on my leftmost screen (I have 3 displays) yet the app is clearly maximizing to a "ghost" 4th display to the left of that one. All attempts to "grab" the window to make it visible and interactable have failed. 

### Expected Behavior

I expect to be able to interact with the app.

### Steps To Reproduce

1. Open app
2. It appears to open on the main display for a split second
3. It opens on the ghost display

### YTMDesktop

1.13.0 I think (I can't check because I can't interact with the app)

### OS

Windows

### OS Version

11 21H2

### Arch

x64

### Installation way

.exe

### Anything else?

![2022-08-09_08-39](https://user-images.githubusercontent.com/5086636/183649581-260d9623-b0e7-4617-85a4-295db31a2d10.png)
![2022-08-09_08-40](https://user-images.githubusercontent.com/5086636/183649585-89fb785e-6045-4172-b57a-841fcdae4744.png)

**Comment by eobet** [comment] 2022-08-16 08:54
I also have the same issue now when I try a laptop with an external display.

I can see the little YTM desktop window fly off diagonally out of the desktop and the display every time I click on the taskbar icon, but windows + shift + left arrow does not bring it back.

Further, if I click in the task manager to activate the miniplayer, I do get a new window centered in my display, but it only contains a spinner that never stops loading...

Also, if I click on the thumbnail play buttons nothing happens. I just noticed that this behavior stays even if I disconnect the external display. Is this app permanently broken now?

**Comment by LordDemonos** [comment] 2022-08-23 04:00
This is exactly how YTM desktop behaves on my computer now as well. I can see the screen just open and fly off to the right, past my screen's edge. miniplayer never loads when I try to switch to it. I reinstalled but there was no change in behavior.

**Comment by JoshMayberry** [comment] 2022-09-09 15:27
Mine does this a lot too.
It's because there is a config file that says where the window should appear. (Seems like a bad idea for exactly this reason).

You can edit the config file by going to `%appdata%/youtube-music-desktop-app/config.json`.
Look for `window-position` and change the `x` and `y` to zero (Mine is usually -32000 for both when this happens).

**Comment by waggz81** [comment] 2022-09-21 13:39
I also have this issue. I used to be able to leave the player on a second monitor in portrait orientation and when I reopened the app it would be where I left it. Now it opens on the main monitor and flies off to the top of the 2nd monitor. I have to use alt+space m to move it back down to where I can see it.

**Comment by MarlonAntonioLG** [comment] 2022-09-30 03:09
> ### Consent
> * [x]  I verified that there is no open/closed issue for the same subject.
> * [x]  I understand that **YTMDesktop have NO affiliation with Google or YouTube**
> 
> ### Current Behavior
> The app will only maximize off screen to a ghost display, and any attempts to bring the window into view fail. It's hard to explain so I've attached 2 screenshots. This is on my leftmost screen (I have 3 displays) yet the app is clearly maximizing to a "ghost" 4th display to the left of that one. All attempts to "grab" the window to make it visible and interactable have failed.
> 
> ### Expected Behavior
> I expect to be able to interact with the app.
> 
> ### Steps To Reproduce
> 1. Open app
> 2. It appears to open on the main display for a split second
> 3. It opens on the ghost display
> 
> ### YTMDesktop
> 1.13.0 I think (I can't check because I can't interact with the app)
> 
> ### OS
> Windows
> 
> ### OS Version
> 11 21H2
> 
> ### Arch
> x64
> 
> ### Installation way
> .exe
> 
> ### Anything else?
> ![2022-08-09_08-39](https://user-images.githubusercontent.com/5086636/183649581-260d9623-b0e7-4617-85a4-295db31a2d10.png) ![2022-08-09_08-40](https://user-images.githubusercontent.com/5086636/183649585-89fb785e-6045-4172-b57a-841fcdae4744.png)

Go to screen options and switch the screens. For me it was easy because I only have two screens.

I recently moved my second monitor to the right, and also in the display options. So I deduced that it opened to the orientation it had before, to a ghost monitor. In display options I moved the second monitor to where I had it before, opened th program and voila, working again!

Move the monitor back to where you had it, with the program open on the monitor, accept the changes and you should no longer have problems

**Comment by mannfuri** [comment] 2022-10-12 10:49
> Mine does this a lot too. It's because there is a config file that says where the window should appear. (Seems like a bad idea for exactly this reason).
> 
> You can edit the config file by going to `%appdata%/youtube-music-desktop-app/config.json`. Look for `window-position` and change the `x` and `y` to zero (Mine is usually -32000 for both when this happens).

thank man~
this helps.

**Comment by Alipoodle** [comment] 2023-07-23 14:23
Duplicate of #918

**Closed by Alipoodle** 2023-07-23 14:23 UTC
