### ISSUE TITLE
Can't switch 2nd factor method

### ISSUE THREAD

**Issue by aanno** [ytmdesktop/ytmdesktop#417] opened 2020-09-27 15:35 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
Can't switch 2nd factor method

 **To Reproduce**
 1. For 'Mediathek', you have to log in with your google account
 2. My google account is secured by 2nd factor. I use several '2nd factors' (security key/token, google authenticator, ...) 
 3. The login process don't let you choose the '2nd factor'. In my case 'security key' is pre-selected, but on the device I want to login, this is not possible, hence I want to use 'google authenticator'
 4. However, I can't switch. Bummer! No login, no 'Mediathek'.

 **Expected behavior**
It should be possible to switch the '2nd factor' the way it is possible when you use the browser to log into google mail.

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***linux*** ubuntu 20.04 aka focal
 * OS version: ***5.4.0-48-generic***
 * Arch: ***x64***
 * Installation way: ***snapcraft***

**Comment by aanno** [comment] 2020-09-27 15:38
BTW, I tried an 'app specific password' as '2nd factor' replacement. But this does not work, either.

**Comment by irlevesque** [comment] 2020-12-14 16:26
This is a problem for me using the DMG on my Mac, as well. Also tried using an app-specific password but the login is denied using the app password and hangs indefinitely waiting for the security key when using my account password.

**Comment by tgr** [comment] 2020-12-15 06:05
Handling app passwords seems important on its own as it is more secure than giving your credentialsto a relatively untrusted app, so filed as a separate issue: #531

**Comment by tgr** [comment] 2020-12-20 01:08
Using a security key doesn't seem to be working either, so it's not just a matter of switching - login for 2FA-enabled accounts just seems completely broken.

**Comment by TheHippo** [comment] 2020-12-29 23:34
It's not really a fix, but using the AppImage worked for me. Not ideal, but it gets you logged in.

**Comment by jimmyd-be** [comment] 2021-01-12 17:49
> It's not really a fix, but using the AppImage worked for me. Not ideal, but it gets you logged in.

I tried it with me and it does not work. Keeps loading the 2-way authentication screen like it is on the snap version.

**Comment by unbelll** [comment] 2021-01-28 21:39
Still issue in v1.14.0

**Comment by jimmyd-be** [comment] 2021-05-24 11:54
Any progress on this one? Becuase of this I cannot use the app.

**Comment by Alipoodle** [comment] 2024-02-05 15:58
Duplicate of #390

**Closed by Alipoodle** 2024-02-05 15:58 UTC
