### ISSUE TITLE
 Youtube Music Play only Audio Option

### ISSUE THREAD

**Issue by Captured-Heart** [ytmdesktop/ytmdesktop#1003] opened 2022-07-16 14:38 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

An option to play only the audio of the music.... Just like in other music apps like spotify

### Solution

Give an option to play Video or Audio in the seettings

**Comment by Alipoodle** [comment] 2022-07-16 16:34
Dupe of #46
Please note that a "Basic" implementation has "hacked" into 1.14.2 by displaying the Premium only thing for the Song/Video Switcher 👀
![image](https://user-images.githubusercontent.com/17199186/179363809-47247494-177c-4805-862a-d82fd46c4e09.png)

**Closed by Alipoodle** 2022-07-16 16:34 UTC
