### ISSUE TITLE
Keyboard shortcuts not working on 1.12.1

### ISSUE THREAD

**Issue by guaycuru** [ytmdesktop/ytmdesktop#304] opened 2020-08-10 17:00 UTC
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Keyboard shortcuts are not working on YTMD 1.12.1.
I have a Microsoft Wired Keyboard 600 which has a Play/Pause key, and also a Razer Lancehead Mouse in which I customized one of its keys to act as a Media Play/Pause button and a Edifier Bluetooth headset with a play/pause button. All of them were working fine on Google Play Music and Google Play Music Desktop, but the keyboard and mouse buttons are not working on YTMD v1.12.1.

**To Reproduce**
1. Set the keyboard shortcut to Play/Pause using your preferred media key.
2. Try to use it.
3. Notice how it does not work as expected even when YTMD is in the foreground.

**Expected behavior**
I expect that shortcut to work on the keyboard, the mouse and the headset.

**Screenshots**

![image](https://user-images.githubusercontent.com/1985884/89808950-4c583e80-db11-11ea-92b6-51e0d504173a.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***Windows***
 * OS version: ***Windows 10 Pro 2004***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by rickinbsb** [comment] 2020-08-10 18:01
is windows media integration enabled?

**Comment by guaycuru** [comment] 2020-08-10 18:03
Do you mean Windows 10 media service?
If so, it is:

![image](https://user-images.githubusercontent.com/1985884/89815104-9560c080-db1a-11ea-8e41-2e12ba5b2c18.png)

If not I don't know what you're talking about...

**Comment by adlerluiz** [comment] 2020-08-10 18:07
you do not need to define ```MediaPlayPause``` in the custom shortcuts, as by default ```MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause``` are already defined by default

**Comment by guaycuru** [comment] 2020-08-10 18:11
I tried leaving the default shortcuts unchanged but they were not working, so I tried setting play/pause to `MediaPlayPause` (which is what my keyboard play/pause button is detected as being) and it also didn't work...

**Comment by adlerluiz** [comment] 2020-08-10 18:12
can you test this version? - https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.2-RC2/YouTube.Music.Desktop.App.Setup.1.12.2-RC2.exe

**Comment by adlerluiz** [comment] 2020-08-10 18:20
can you test this version? - https://github.com/ytmdesktop/ytmdesktop/releases/download/v1.12.2-RC2/YouTube.Music.Desktop.App.Setup.1.12.2-RC2.exe

**Comment by guaycuru** [comment] 2020-08-10 18:22
Unfortunately v1.12.2-RC2 did not work either

**Comment by adlerluiz** [comment] 2020-08-10 18:29
Strange, because I also have a microsoft keyboard and a razer deathadder mouse that normally works with a keyboard, mouse, multimedia keys and even the bluedio headset, I will investigate and see what can be done, do you use any program to simulate the keyboard?

**Comment by guaycuru** [comment] 2020-08-10 18:40
I don't have anything unusual regarding keyboard and/or mouse. The weird thing is that all 3 of them (keyboard, mouse and Bluetooth headset) work on Google Play Music Desktop Player.

**Comment by jfaranda7** [comment] 2020-08-11 05:07
I just want to confirm that my Razer Naga media buttons are not working either. I have the service checked too.

**Comment by DioVayne** [comment] 2020-08-12 06:31
I have the same problem. Trying out different setting even resulted in the app only running in the background without taskbar icon. The only way to stop it is through Task Manager.
I tried installing RC2. Play/Pause still not working. The icon is back but now clicking on the settings-icon doesn't do anything. Is there a way to reset all settings?

**Comment by shadshack** [comment] 2020-08-12 17:39
I'm having the same issue, across 2 computers (Work and Home, got it working on Home PC eventually). MediaNextTrack, MediaPreviousTrack, MediaStop and MediaPlayPause won't work at all. Default hotkeys work globally (Ctrl+Shift+Space to pause), just not what I'd like to use since dedicated media buttons exist for a reason.

My home computer uses a Corsair STRAFE RGB keyboard, the media keys work fine for any other media player. Had to enable BOTH "Enable Windows 10 media service" and "Show track information next to Windows 10 volume bar" to get it to work finally. Neither the Corsair keyboard media controls nor my bluetooth headphones media controls would work otherwise.

Work PC is a Razer Blackwidow Chroma, won't work no matter what I do, even after the same "fixes" I described above for my home PC.  Also tried the 1.12.2-RC2 and no change.

**Comment by jaimbo** [comment] 2020-08-13 16:06
Also having the same issue with a Corsair K70 RGB Lux, tried @shadshack suggestion above but that didn't work either.

**Comment by djohannes** [comment] 2020-08-14 19:14
@guaycuru I can always suggest to remove the GPM extension from chrome, as it causes a lot of issues with media keys for other programs.

**Comment by shadshack** [comment] 2020-08-14 19:17
@djohannes That actually just fixed it for me on my Work computer I mentioned above. That actually makes it work without needing the "Enable Windows 10 media service" and "Show track information next to Windows 10 volume bar" options enabled.

**Comment by guaycuru** [comment] 2020-08-14 19:19
@djohannes I had already removed the extension I'm afraid... Still not working :(

**Comment by djohannes** [comment] 2020-08-14 19:59
@guaycuru When you close YTMdesktop and you go to let's say normal YT in Chrome, do your media keys work there if you play a video? Because they should :) If not, there is still some other app "taking over" your media keys (maybe the GPM desktop app if you have it on auto start).

**Comment by jfaranda7** [comment] 2020-08-14 23:27
@djohannes thanks for that, removing GPM fixed it

**Comment by guaycuru** [comment] 2020-08-18 19:09
@djohannes Hmm that's odd, they do not work, but I don't think they ever worked on YouTube... I tried closing everything, and even launching chromium with no extensions and still I can't control YouTube using media keys... Google Play Music Desktop still works fine with media keys.

**Comment by ZombieAnidata** [comment] 2020-08-18 19:23
> @djohannes Hmm that's odd, they do not work, but I don't think they ever worked on YouTube... I tried closing everything, and even launching chromium with no extensions and still I can't control YouTube using media keys... Google Play Music Desktop still works fine with media keys.

If you have Google Play Music Extension on chrome it will interfear and it will not work go look at your extensions and remove it.

**Comment by jaimbo** [comment] 2020-08-18 19:35
So I discovered that the media controls work on my K70 with YouTube Music Desktop if I hold the control key and then press the media control? Hope this helps

**Comment by guaycuru** [comment] 2020-08-18 19:35
@jaimbo Right, but I don't have it, removed over a month ago :)

**Comment by djohannes** [comment] 2020-08-19 07:24
> @djohannes Hmm that's odd, they do not work, but I don't think they ever worked on YouTube... I tried closing everything, and even launching chromium with no extensions and still I can't control YouTube using media keys... Google Play Music Desktop still works fine with media keys.

@guaycuru Well, then some other app is still taking over your media keys :/ Did you also remove the GPM desktop app ?

**Comment by BigFish7** [comment] 2020-08-19 14:46
I resolved it by removing the Google Play Muisc extension in Google Chrome

**Comment by regisz** [comment] 2020-08-30 13:13
> I resolved it by removing the Google Play Muisc extension in Google Chrome

@BigFish7 this was the solution for me too, thx a lot! 👍

**Comment by lifesoccult** [comment] 2020-09-10 19:00
I'm having this issue on MacOS Catalina (10.15.6). Media keys work fine in webapp (music.youtube.com).

**Comment by guaycuru** [comment] 2020-09-21 22:54
Sorry for the delay. I did remove the Google Play Music extension AND desktop app, but still my keyboard / mouse shortcuts don't work with ytmdesktop...

**Comment by Infinity315** [comment] 2020-12-06 13:07
For future Googlers who have Chrome installed.  Chrome is hijacking your media keys.  I found that if Chrome is running that my media keys would stop working (save for the stop media key which acted as a play/pause) and media key functionality would return as soon I closed Chrome.  

The fix is:

_You will lose all media key functionality for Chrome._

1. Goto: `chrome://flags/#hardware-media-key-handling` in your Chrome browser.  
2. Change this setting: `Hardware Media Key Handling` from `Enabled` or `Default` to `Disabled`
3. Restart your PC ( I found this was a necessary step (probably to restart some Windows media service )

**Comment by scarletswalking** [comment] 2020-12-30 22:49
> For future Googlers who have Chrome installed. Chrome is hijacking your media keys. I found that if Chrome is running that my media keys would stop working (save for the stop media key which acted as a play/pause) and media key functionality would return as soon I closed Chrome.
> 
> The fix is:
> 
> _You will lose all media key functionality for Chrome._
> 
> 1. Goto: `chrome://flags/#hardware-media-key-handling` in your Chrome browser.
> 2. Change this setting: `Hardware Media Key Handling` from `Enabled` or `Default` to `Disabled`
> 3. Restart your PC - I found this was a necessary step ( probably to restart some Windows media service )

This did not work for me. CTRL+play/pause key also did not work. It doesn't make a difference if it is focused or not, either. I uninstalled/reinstalled YTM, and I deleted the other streaming media players from my computer, including all the attached files.

**Comment by mingjun97** [comment] 2021-01-26 21:55
> I'm having this issue on MacOS Catalina (10.15.6). Media keys work fine in webapp (music.youtube.com).

This may be caused by the malfunction of our dependency Electron. And now got fixed in pre-release 1.14.0. If it still doesn't work. Navigate to [System Preference] -> [Security & Privacy] -> [Accessbility], unlock and uncheck then check again YTMDesktop to got fixed.

Thanks!

**Closed** 2021-01-26 21:55 UTC
Labels: bug
