### ISSUE TITLE
Sign in button is not working

### ISSUE THREAD

**Issue by fronders** [ytmdesktop/ytmdesktop#646] opened 2021-03-01 13:09 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
I have logged out through the Google Account console. When I open YTMDesktop I am signed out. When I click the "SIGN IN" button nothing happens (no popup or page loading). Tried clicking 3 dots and "Get YouTube Premium" - a header opens up, but clicking "TRY IT FREE" also gives no action. Rebooting PC did not help

 **To Reproduce**
 1. Sign out (through Google Account page)
 2. Open YTMDesktop
 3. Click "SIGN IN"
 4. Nothing happens, no popup or page load

 **Expected behavior**
Google Sign In prompt expected, but nothing happens

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19041***
 * Arch: ***x64***
 * Installation way: ***.exe***

**Comment by uygary** [comment] 2021-04-23 16:58
Just to confirm: This occasionally happens to me as well. In fact, whenever the existing login expires and the app signs me out, this exact issue happens.
I did notice though, that _sometimes_ clicking the "Sign in" button **repeatedly** and with a **high enough frequency**, it does work.

**Comment by williameum** [comment] 2021-06-28 16:23
In my case the sign in button, not working any time

**Comment by Daniel9132** [comment] 2021-07-24 21:18
Sign in window doesn't appear when i click on the top right or i like a song. Seems like the underlying version is outdated and not accepted by Google anymore.
I had the app installed for a long time with my account singed in. I started it recently and i was logged out and login window doesn't appear.
I reinstalled just to make sure my installation isn't broken, didn't help i get the same result.

**Comment by uygary** [comment] 2021-08-23 18:32
Duplicate of #432.

**Comment by Alipoodle** [comment] 2022-01-03 20:23
Closing due to dupe of #432

**Closed by Alipoodle** 2022-01-03 20:23 UTC
