### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by mchungy** [ytmdesktop/ytmdesktop#371] opened 2020-09-10 05:31 UTC
- [ ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

**Describe the bug**
This happens when you search for YouTube Music Desktop App and click open mean while having YouTube music opened

Always gives you a a pop out and opens another YouTube Music application

**To Reproduce**
1. Have YouTube Music opened already
2. Go to search menu
3. Search YouTube Music App 
4. Open it
5. See error

**Expected behavior**
Opens the current YouTube Music application that's running rather than opening another one causing the pop out.

**Screenshots**
https://user-images.githubusercontent.com/71059491/92684796-e0176780-f368-11ea-9c98-0545a2f65034.png
**Environment (please complete the following information):**
 * YTMDesktop version: ***1.13.0***
 * OS: ***Windows*** 
 * OS version: ***19041.508***
 * Arch: ***x64***
* Installation way: ***Exe***

**Comment by adlerluiz** [comment] 2020-09-14 03:46
this is a known error because when he opens the second instance he tries to hear the door already in use, but soon the fix will be available

**Comment by kudlav** [comment] 2020-12-09 19:02
Same error and same cause. Any progress here?
![obrazek](https://user-images.githubusercontent.com/11516259/101674889-5a838080-3a59-11eb-9fd4-a6b37d4c5320.png)

**Comment by mingjun97** [comment] 2021-01-27 09:18
I cannot reproduce this problem locally since I'm using mac. I believe apply below patches could solve this issue. Could anyone try it?

```diff
diff --git a/main.js b/main.js
index cc7f29f..27bcc90 100644
--- a/main.js
+++ b/main.js
@@ -2026,9 +2026,9 @@ ipcMain.on('log', (dataMain, dataRenderer) => {
     else writeLog(dataRenderer)
 })
 
-if (settingsProvider.get('settings-companion-server')) companionServer.start()
+if (settingsProvider.get('settings-companion-server') && gotTheLock) companionServer.start()
 
-if (settingsProvider.get('settings-genius-auth-server')) {
+if (settingsProvider.get('settings-genius-auth-server') && gotTheLock) {
     geniusAuthServer.start()
 }
```

Usage:
Save above code as `fix.patch` to the ytmd folder.
`git apply fix.patch`

Thanks!

**Comment by M2ast** [comment] 2022-07-05 04:12
Got this error tonight 5 July 2022:

YTD Version: 1.13.0
Windows 11 Business ver. 21H2 build. 22000.739

A JavaScript error occurred in the main process
Uncaught Exception:
Error: listen EADDRINUSE: address already in use 0.0.0.0:9863
at Server.setupListenHandle [as_listen2] (net.js:1313:16)
at listenInCluster (net.js:1361:12)
at doListen (net.js:1500:7)
at process TicksAndRejections (internal/process/task_queues.js:85:21)

Picture
![image](https://user-images.githubusercontent.com/102571259/177247688-7c12a7aa-a721-4e2d-bb7d-61aedfd7041b.png)

Keep up the great work on this!

**Comment by gambuzino-wonder** [comment] 2023-12-24 21:07
Having same issue for some months and no update seems to be resolving it.

**Comment by Alipoodle** [comment] 2024-01-29 10:25
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:25 UTC
Labels: Bug, YTMD V1
