### ISSUE TITLE
Add setting to ignore videos or disable video playback

### ISSUE THREAD

**Issue by RileyXX** [ytmdesktop/ytmdesktop#964] opened 2022-05-14 00:51 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

When I run youtube music in minimized to the tray sometimes video files will come up and start playing instead of audio files. The videos suck up resources so when I'm gaming and a video file starts playing in the background (without my knowledge) my game will start lagging.

### Solution

Add setting to disable video playback and/or setting to ignore videos altogether

**Comment by Alipoodle** [comment] 2022-05-14 08:13
This should be natively in YouTube music now with the Audio/Video selector?

This doesn't work on 100% of videos but a good 95% works.
And I said Video, anything music should be fully supported for Music only?

**Comment by Hershey025** [comment] 2022-05-14 08:31
This feature is only available for ytm premium users. You will require ytm premium to get the video/audio switcher.

**Comment by Alipoodle** [comment] 2022-05-15 18:11
This is a feature which is now enabled within the 1.14.2 feature for ALL users, as the stuff for toggling the Audio/Video Switcher exists within YTM at all times but is hidden behind some code.

For the time being, I'm considering this a good enough implementation, and to ultimately improve the implementation, getting YTM Premium is the best bet.

Duplicate of #46

**Closed by Alipoodle** 2022-05-15 18:11 UTC
