### ISSUE TITLE
Text labels on dock dropdown are using raw label values

### ISSUE THREAD

**Issue by clayton-sayer** [ytmdesktop/ytmdesktop#995] opened 2022-07-11 16:46 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

After upgrading YTMD to version 1.14.2 I noticed that the text on the dock dropdown menu use the raw label values, such as `MEDIA_CONTROL_PLAY_PAUSE` and `LABEL_EXIT` rather than the translation values, like `play/pause` and `exit`. Previously on 1.14.0 this text would use the correct translation file. See the screenshot below for an example.

A likely cause of the issue is an error message which pops up when I open up the app, which is also screenshotted below.

I am running on an M1 MBP with my region being Canada and the language being set to `English (UK)`. I've tried setting my language to en-US but that has not helped.

### Expected Behavior

I expect that the dock dropdown has the correct text labels provided.

### Steps To Reproduce

1. Download t[he 1.14.2 release](https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2) for OSX and install it.
2. Open the app
3. Click the dock dropdown.

### YTMDesktop

1.14.2

### OS

OSX

### OS Version

12.4 Monterey

### Arch

ARM64

### Installation way

DMG from Github

### Anything else?

<img width="428" alt="Screenshot 2022-07-11 at 8 36 51 AM" src="https://user-images.githubusercontent.com/104379391/178313834-a2e6b299-1d5b-4f0a-ae25-a98d30759320.png">

<img width="270" alt="Screenshot 2022-07-11 at 9 38 20 AM" src="https://user-images.githubusercontent.com/104379391/178314502-4a3a7828-4752-42dc-b2d3-ad3184b66ed6.png">

Transcription of the error box:
```
A JavaScript error occurred in the main process

Uncaught Exception:
TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
at makeCallback (fs.js:157:11)
at Object.unlink (fs.js:1129:14)
at ClientRequest.<anonymous> (/Applications/YouTube Music Desktop App.app/Contents/Resources/app.asar/src/providers/translateProvider.js:50:16)
at ClientRequest.emit (events.js:315:20)
at TLSSocket.socketErrorListener (_http_client.js:426:9)
at TLSSocket.emit (events.js:315:20)
at emitErrorNT (internal/streams/destroy.js:92:8)
at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by Alipoodle** [comment] 2022-07-12 07:17
Duplicate of #967

**Closed by Alipoodle** 2022-07-12 07:17 UTC
