### ISSUE TITLE
Login Issure

### ISSUE THREAD

**Issue by MrModernFox** [ytmdesktop/ytmdesktop#1022] opened 2022-09-03 01:18 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Im trying to login abut when ever I do that it says this can anyone help?
![Screenshot 2022-09-03 111506](https://user-images.githubusercontent.com/90390002/188250203-96512bbc-373a-45ed-bedc-26ea701b39ac.png)

### Expected Behavior

I can Log in my account and start listening to my music

### Steps To Reproduce

1. Sign in
2. Login in to your account
3. Could't sign you in *Try using a different browser*

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by qinrui96** [comment] 2022-09-05 09:19
I face the same problem, I solve this problem as below :
1. log in gmail by safari
2. try log in YouTube desktop app again
hoping it's useful for you

**Comment by MrModernFox** [comment] 2022-09-05 21:55
well i dont think so and i dont have an iphone and by reading that i dont think it sounds right

**Comment by RyanBlakeIT** [comment] 2022-09-06 04:39
I am running Manjaro Linux (based on Arch) and I had the same behavior.  To resolve, with YTM installed but not running, I reinstalled Electron with pacman -S electron and then I was able to sign in.  I understand this is regarding Windows, but was hopeful that this would assist the devs in finding a solution.

**Comment by tekunikaru** [comment] 2022-09-06 11:57
I'm on Windows Server 2022 Standard

I installed YTMD and tried to log in, after failing I tried similar steps mentioned by [qinrui96](https://github.com/qinrui96)
> 1. log in gmail by safari
> 2. try log in YouTube desktop app again

With YTMD installed but not running, I logged into my Google account on Edge without any problems.
Then I opened YTMD and managed to log in without any problem.

Maybe it's a combination of suspicious activities that makes Google think it's unsafe to start the login process, probably using a known safe browser (Edge) raises the trust level enough to accept the login attempt.

**Comment by Teslafly** [comment] 2022-09-06 16:18
I am also having this issue on windows 11.
except logging in using a different browser doesn't work. 

This is the learn more link: https://support.google.com/accounts/answer/7675428?hl=en


> To help protect your account, Google doesn’t let you sign in from some browsers. Google might stop sign-ins from browsers that:
> 
> - Don’t support JavaScript or have JavaScript turned off
> - Have unsecure or unsupported extensions added
> - Are being controlled through software automation rather than a human
> - Are embedded in a different application

so instead of using the electron browser, using the system browser for login may be preferable.

**Comment by coarsehorse** [comment] 2022-09-07 12:31
It's fixed in [1.14.2](https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.2)

**Comment by Alipoodle** [comment] 2022-09-08 18:27
Duplicate of #866

> Are embedded in a different application
This is what we come under, As we're Electron.

> Alternatives
We can't use OAuth to Sign into your YouTube Music, we need the full Sign in.
We can't do PWA as again, we're trying  to not be a YTM PWA and a Desktop application.

**Closed by Alipoodle** 2022-09-08 18:27 UTC
