### ISSUE TITLE
Need option to enable "Cast..." button 

### ISSUE THREAD

**Issue by xmario99** [ytmdesktop/ytmdesktop#233] opened 2020-07-09 20:08 UTC
Need option to enable "Cast..." button  in the app in order to send audio to a Chromecast device
Cheers!

**Comment by rickinbsb** [comment] 2020-07-10 01:02
Hey there, thanks for using this app!
I'm closing this as a duplicate of #29

**Closed by rickinbsb** 2020-07-10 01:02 UTC

**Comment by justin-romano** [comment] 2020-08-29 02:00
And please make it better than the native chrome browser implementation. Really stutterey on slower machines
