### ISSUE TITLE
Keyboard shortcuts intercept and prevent other applications from responding to them

### ISSUE THREAD

**Issue by KAJed82** [ytmdesktop/ytmdesktop#220] opened 2020-06-29 16:13 UTC
The keyboard shortcuts do not appear to be customizable and they are being 'eaten' by the app. CTRL-SHIFT-Space is a common Visual Studio intellisense shortcut but I cannot use it while the application is active because they are being intercepted.

**Comment by rickinbsb** [comment] 2020-07-01 16:44
Thank for using this app! Customizable shortcuts are planned to be implemented.

 I'm closing this as a duplicate of #3

**Closed by rickinbsb** 2020-07-01 16:44 UTC
