### ISSUE TITLE
Increase/Decrease volume shortcuts used in the app even if it is running in the background.

### ISSUE THREAD

**Issue by asre244** [ytmdesktop/ytmdesktop#1140] opened 2023-07-26 05:02 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Hotkeys - for example, Ctrl+Shift+Up/Down for increasing and decreasing volume is used in the app even if the app is running in the background. This prevents from using the same combination of keys in any other app, for example, in Microsoft Excel.

### Expected Behavior

I expect the hotkeys to be used when actually using the app and not when it is running in the background. The workaround for this is to disable the shortcut keys but this more of a bypass than actually addressing the issue. 

### Steps To Reproduce

1. Open the app
2. Play any song/video
3. Minimise the app
4. Open Microsoft Excel
5. Use Ctrl+Shift+Down to select all rows in the column below the selected row in excel. This actually decreases the volume in the app.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Hershey025** [comment] 2023-07-26 07:26
You can change the combination of the keys for increasing or decreasing the volume.

**Comment by Alipoodle** [comment] 2023-07-31 16:00
This is intended behaviour, although we had discussed to remove the Keybinds.
This will be the case in V2.

Although I do want to consider adding a `Local` vs `Global` Toggle in V2 although see how this is considered / would work.

**Comment by Alipoodle** [comment] 2024-02-04 18:27
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-04 18:27 UTC
Labels: More Info Needed
