### ISSUE TITLE
Corsair K70 Media keys not working

### ISSUE THREAD

**Issue by jondominguezv** [ytmdesktop/ytmdesktop#252] opened 2020-07-14 20:04 UTC
I have a Corsair K70 lux keyboard and I when I have ytmdesktop open the media keys on the keyboard don't work with it. The media keys work with other music apps that I've used. I'm on Windows 10.

**Comment by rickinbsb** [comment] 2020-07-14 20:15
might be related to #100

**Comment by kirebyte** [comment] 2020-07-15 16:06
I discovered something weird, Kubuntu user here, cooler master keyboard in my case.
If I keep the options window open and press the multimedia keys while focused on that window they work. But I lose the focus, close that window or switch desktop it stops working. Might be related to the way it's listening to keys.

@jondominguezv would you mind trying these steps for me?
1) Open the program and play a song.
2) Open the settings menu (top right cog button)
3) Press pause.
4) Song actually pauses.

**Comment by rickinbsb** [comment] 2020-07-15 16:20
I believe this can be caused by some other app taking over control of mediakeys when ytm is not focused

**Comment by jondominguezv** [comment] 2020-07-15 17:13
> I discovered something weird, Kubuntu user here, cooler master keyboard in my case.
> If I keep the options window open and press the multimedia keys while focused on that window they work. But If I lose the focus, close that window or switch desktop it stops working. Might be related to the way it's listening to keys.
> 
> @jondominguezv would you mind trying these steps for me?
> 
> 1. Open the program and play a song.
> 2. Open the settings menu (top right cog button)
> 3. Press pause.
> 4. Song actually pauses.

I tried this and it did not pause.

**Comment by jondominguezv** [comment] 2020-07-23 16:06
I enabled Start on Boot and now the media keys seem to work every time.

**Comment by rickinbsb** [comment] 2020-08-04 00:46
Can you please check if this is fixed on v1.12?
We added deeper media integration with the system

**Comment by jondominguezv** [comment] 2020-08-04 03:31
Looks like its working good.

**Comment by jondominguezv** [comment] 2020-08-04 03:31
> Can you please check if this is fixed on v1.12?
> We added deeper media integration with the system

Looks like its working good.

**Comment by rickinbsb** [comment] 2020-08-04 03:37
awesome!

**Closed** 2020-08-04 03:37 UTC
Labels: bug
