### ISSUE TITLE
Feature request: Adblocker

### ISSUE THREAD

**Issue by jigar007** [ytmdesktop/ytmdesktop#160] opened 2020-05-12 04:44 UTC
The app is really awesome, just one feature which I have currently in browser and missing is adblocker. 
I am iOS developer, know very little about node and javascript, still if I can contribute something in that I am more than happy to do.

**Comment by gnahum12345** [comment] 2020-05-17 06:16
bump this feature request.

**Comment by deprale** [comment] 2020-05-27 00:42
this app is so getting DMCA'd if they do add adblocker lol
just block them yourselves its not that hard

**Comment by rickinbsb** [comment] 2020-06-01 23:37
I'm closing this as it is a duplicate of #114

**Closed by rickinbsb** 2020-06-01 23:37 UTC
Labels: duplicate
