### ISSUE TITLE
Google was blocked in my computer! So i want to use $>./youtube-music-desktop-app --proxy-server=127.0.0.1:1234, but it does't work! And then  how to use YTMdesktop with the right format of proxy '--proxy-server=127.0.0.1:1234'?

### ISSUE THREAD

**Issue by askuyue** [ytmdesktop/ytmdesktop#886] opened 2021-12-27 14:35 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Google was blocked in my computer! So i want to use $>./youtube-music-desktop-app --proxy-server=127.0.0.1:1234, but it does't work! And then  how to use YTMdesktop with the right format of proxy '--proxy-server=127.0.0.1:1234'?

### Alternatives

Google was blocked in my computer! So i want to use $>./youtube-music-desktop-app --proxy-server=127.0.0.1:1234, but it does't work! And then  how to use YTMdesktop with the right format of proxy '--proxy-server=127.0.0.1:1234'?

### Anything else?

Google was blocked in my computer! So i want to use $>./youtube-music-desktop-app --proxy-server=127.0.0.1:1234, but it does't work! And then  how to use YTMdesktop with the right format of proxy '--proxy-server=127.0.0.1:1234'?

**Comment by Alipoodle** [comment] 2021-12-27 15:08
Duplicate of #178

**Closed by Alipoodle** 2021-12-27 15:08 UTC

**Comment by Alipoodle** [comment] 2021-12-27 15:12
Theoretically using the command provided should work due to starting electron up with a proxy.
However I cannot guarantee it will work.

Previously, I've suggested someone to use `%localappdata%\programs\youtube-music-desktop-app\YouTube Music Desktop App.exe <Add flags here>` and it has worked... however given the prompt style you are showing me, It maybe different for Mac/Linux

**Comment by JBPhoenix** [comment] 2022-01-10 02:50
@askuyue Not tried on mac/linux but, on windows for me, the proxy argument needed quotation marks around the address:port value.
e.g --proxy-server="127.0.0.1:1234"

**Comment by yuzh496** [comment] 2025-08-13 02:12
@JBPhoenix thanks ，it works （ linuxmint 22.1）
