### ISSUE TITLE
No possibility to manage YTMDesktop via bluetooth devices

### ISSUE THREAD

**Issue by KPOCT** [ytmdesktop/ytmdesktop#315] opened 2020-08-13 14:56 UTC
**Environment:**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***linux*** (ubuntu 20.04)
 * OS version: ***5.4.0-42-generic***
 * Arch: ***x64***

**Comment by guaycuru** [comment] 2020-10-30 20:31
Possible duplicate of https://github.com/ytmdesktop/ytmdesktop/issues/304 ?

**Comment by Alipoodle** [comment] 2024-02-05 15:55
This issue lacks a lot of information so I'm closing it...
Please re-open a new ticket with more information explaining what you are needing help with / what features you want.

**Closed by Alipoodle** 2024-02-05 15:55 UTC
Labels: Enhancement, Help wanted
