### ISSUE TITLE
[BUG] Windows Media thing shows outdated info when song changes.

### ISSUE THREAD

**Issue by TotallyNotInUse** [ytmdesktop/ytmdesktop#402] opened 2020-09-21 22:46 UTC
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Sometimes the Windows Media thingy shows outdated info on the song.

**To Reproduce**
1. Play music with Windows Media showing info.
2. Wait for it to happen.

**Expected behavior**
To show the correct info

**Screenshots**
![image](https://user-images.githubusercontent.com/56458705/93828948-b3e1cd80-fc29-11ea-969f-925dde629583.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***V1.13***
 * OS: ***Windows***
 * OS version: ***10.19041.508***
 * Arch: ***x64***
* Installation way: ***Auto update (originally installed from releases)***

**Comment by mrmichaelbeck** [comment] 2020-09-23 14:27
I see the same sort of issue.  It seems to display the previous song's information in the title bar of the player window.  Which also shows it on the Windows taskbar.

version 1.13.0 on Windows 10 Enterprise 64bit

**Comment by debmaj2** [comment] 2020-09-25 18:04
Can confirm the same issue

**Comment by TotallyNotInUse** [comment] 2020-11-18 23:37
Can confirm the issue also exists in MacOS

**Comment by Alipoodle** [comment] 2021-10-11 22:12
^ Ticket above seems to have some more information about requirements for this.
However I've been unable to reproduce this issue with the 1.14 & NodeRT Fix.
But will wait until more people are have tested that this works once released.

**Comment by Alipoodle** [comment] 2024-01-29 10:25
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:25 UTC
Labels: Bug, YTMD V1
