### ISSUE TITLE
App crashing when returning from Windows' sleep (power on/awake)

### ISSUE THREAD

**Issue by FASouzaIT** [ytmdesktop/ytmdesktop#1299] opened 2024-02-11 22:00 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

App crashes on Windows after returning from sleep if it was left open.

### Expected Behavior

Return from Windows' sleep (power on/awake) without crashing.

### Steps To Reproduce

1. Open the app
2. Play a song
3. Pause
4. Let or make Windows sleep
5. Power on/awake Windows
6. App will show a crash error and offers options to copy the error log and close or just close.

### YTMDesktop

Version: 2.0.0 | Branch: HEAD | Commit: 6d0abf5

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

Error log:

> YouTube Music Desktop App Crashed
> 
> Environment Details:
>     YouTube Music Desktop App 2.0.0
>     Electron 28.2.0
>     Windows NT 10.0.22631
> 
> Name: Error
> Message: Unhandled error. ('Command failed: 4294967295\n' +
>   "System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
>   '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
>   '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
>   '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '   --- End of inner exception stack trace ---\r\n' +
>   '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
>   '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
>   '   at Squirrel.Update.Program.main(String[] args)\r\n' +
>   '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
>   "---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
>   '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
>   '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
>   '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
>   '\r\n')
> Cause: Unknown
> 
> Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Command failed: 4294967295\n' +
>   "System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
>   '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
>   '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
>   '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '   --- End of inner exception stack trace ---\r\n' +
>   '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
>   '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
>   '   at Squirrel.Update.Program.main(String[] args)\r\n' +
>   '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
>   "---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
>   '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
>   '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
>   '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
>   '--- End of stack trace from previous location where exception was thrown ---\r\n' +
>   '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
>   '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
>   '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
>   '\r\n')
>     at new NodeError (node:internal/errors:405:5)
>     at AutoUpdater.emit (node:events:506:17)
>     at AutoUpdater.emitError (node:electron/js2c/browser_init:2:3868)
>     at node:electron/js2c/browser_init:2:3444
>     at node:electron/js2c/browser_init:2:5035
>     at ChildProcess.<anonymous> (node:electron/js2c/browser_init:2:4741)
>     at ChildProcess.emit (node:events:517:28)
>     at ChildProcess._handle.onexit (node:internal/child_process:292:12)

**Comment by Alipoodle** [comment] 2024-02-11 22:13
Duplicate of #1266

**Closed by Alipoodle** 2024-02-11 22:13 UTC

**Comment by denkiryu** [comment] 2024-02-13 21:30
Exact same issue, here's the error code:

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0
    Electron 28.2.0
    Windows NT 10.0.22631

Name: Error
Message: Unhandled error. ('Command failed: 4294967295\n' +
  "System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
  '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
  '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
  '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '   --- End of inner exception stack trace ---\r\n' +
  '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
  '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
  '   at Squirrel.Update.Program.main(String[] args)\r\n' +
  '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
  "---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
  '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
  '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
  '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
  '\r\n')
Cause: Unknown

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Command failed: 4294967295\n' +
  "System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
  '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
  '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
  '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '   --- End of inner exception stack trace ---\r\n' +
  '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
  '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
  '   at Squirrel.Update.Program.main(String[] args)\r\n' +
  '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
  "---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'update.electronjs.org'\r\n" +
  '   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)\r\n' +
  '   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)\r\n' +
  '   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
  '\r\n')
    at new NodeError (node:internal/errors:405:5)
    at AutoUpdater.emit (node:events:506:17)
    at AutoUpdater.emitError (node:electron/js2c/browser_init:2:3868)
    at node:electron/js2c/browser_init:2:3444
    at node:electron/js2c/browser_init:2:5035
    at ChildProcess.<anonymous> (node:electron/js2c/browser_init:2:4741)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
