### ISSUE TITLE
Miniplayer Slowly Gets Bigger During Playback

### ISSUE THREAD

**Issue by livejamie** [ytmdesktop/ytmdesktop#379] opened 2020-09-12 01:16 UTC
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
The miniplayer slowly gets bigger during playback

**To Reproduce**
Play music

**Expected behavior**
The miniplayer doesn't get bigger

**Screenshots**
![image](https://i.imgur.com/9kkZHMh.gif)

I get these following errors afterward, the first when trying to resize and the second when trying to close the application.

![image](https://user-images.githubusercontent.com/49513/92983663-bb4eed00-f459-11ea-98aa-c622fa20aaec.png)

![image](https://user-images.githubusercontent.com/49513/92983681-d588cb00-f459-11ea-82ae-1b7efb93325e.png)

It happens with every song and with resize enabled and disabled.

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***exe installer from Github***

**Comment by adlerluiz** [comment] 2020-09-15 22:53
I can't reproduce this error, does it happen with any specific song? video? when you try to resize at some point?

**Comment by NeonLights10** [comment] 2020-09-19 18:31
I was able to reproduce it, happens most consistently when resizing or moving the miniplayer, and then immediately hovering over it to display track information. Happens both with videos and album uploads. It always increases in 4 increments before stopping. 

YTMDesktop version: v1.13.0
OS: Windows
OS version: 10
Arch: x64
Installation way: exe installer from Github

**Comment by dino15309** [comment] 2021-02-12 03:52
I have the same issue except it does not stop after 4 increments it just grows until it fills my screen.

**Comment by mingjun97** [comment] 2021-02-12 06:42
```javascript
            miniplayer.on('resize', () => {
                try {
                    let size = miniplayer.getSize()
                    if (storeMiniplayerSizeTimer)
                        clearTimeout(storeMiniplayerSizeTimer)

                    storeMiniplayerSizeTimer = setTimeout(() => {
                        settingsProvider.set(
                            'settings-miniplayer-size',
                            Math.min(...size)
                        )
                        if (miniplayer) {
                            miniplayer.setSize(
                                Math.min(...size),
                                Math.min(...size)
                            )
                        }
                    }, 500)
                } catch (_) {
                    writeLog({ type: 'warn', data: 'error miniplayer resize' })
                }
            })
```

Looks like there is a self invoking due to the `Timeout` and `on`.

**Comment by mingjun97** [comment] 2021-02-12 07:16
This problem should be gone at next release. But you may now try it by downloading nightly build. :)

**Comment by ScottBeeson** [comment] 2022-02-14 16:29
Same issue. Also installed 1.12.1 and 1.12.0 and both exhibited the same issue. I confirmed the version number in the about page. I'm currently running 1.11 and it does not have the issue. Of course, it has no resizing.

**Comment by ScottBeeson** [comment] 2022-02-14 16:35
Tried https://github.com/ytmdesktop/ytmdesktop/releases/tag/1.14.1 and it's WAY worse.  It's unrecoverable.  Also it remembers the previous size
![ytmdgrowth2](https://user-images.githubusercontent.com/108358/153905948-d0773149-2202-4643-b10b-b831bc14ad8d.gif)
.

**Comment by Alipoodle** [comment] 2022-02-14 17:13
Getting very different behaviour compared to my own. 
I can only make it smaller while Dragging from the edge (which I suggest against hugely, as it's intended to be square)

But ultimately this doesn't follow the original thing as it's not growing in its own but miss growing based upon users resizing requests.

**Comment by ScottBeeson** [comment] 2022-03-14 18:50
I have a new laptop. This no longer presents, with ONE exception... on one of my monitors (USB3 portable monitor) the miniplayer grows _while dragging_.  That's it.

¯\_(ツ)_/¯

**Comment by RebelMoogle** [comment] 2022-08-10 22:45
I'm seeing the same issue (it constantly grows without stopping and I get the same javascript error linked above), however it only occurs on my Alienware laptop (M15 R3) and only on the laptop's screen. 

The laptop's screen is 4K, the other external monitors are 1440p and 2560x1080. 
The 4k laptop screen also has a font/ui scaling of 175% active, so maybe it's connected to that?
It's running Windows 10 and it might be the 'feature' of Win10 where it resizes windows moved between monitors that have different resolutions and scaling?

**Comment by Rayvr9** [comment] 2022-09-24 10:59
Seeing the same error mini player always growing.  Not only on playback or while dragging.
I am using ubuntu 22.04, downloaded from snap store. 
Using  HP Victus Laptop 16.

**Comment by eddieparker** [comment] 2024-01-05 00:41
I see this as well on Windows. I find the problem goes away if I turn Display Scaling to 100% on the monitor in question.

If I put the scaling up to 175% (old man eyes) then it scales constantly when losing focus.

**Comment by Alipoodle** [comment] 2024-01-29 10:25
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:25 UTC
Labels: Bug, In Development, YTMD V1
