### ISSUE TITLE
Use YTM auto play feature upon completion of an album/single instead of restarting the album.

### ISSUE THREAD

**Issue by Noah-A-Schwartz** [ytmdesktop/ytmdesktop#828] opened 2021-09-27 02:31 UTC
- [x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
It's a bit annoying when listening to an album, and it just repeats. I would prefer it to go to autoplay as it helps me find new music. Not sure if this is the intended behavior or not. I can see the auto play playlist and it is enabled, but the app just starts over album instead.

**Describe the solution you'd like**
When listening to any album/single or the like, upon completion, will play from the autoplay queue, instead of restarting the album. This is how it works in the YTM official app if it is enabled.

**Describe alternatives you've considered**

**Additional context**
![YouTube_Music_Desktop_App_2021-09-26_22-29-10](https://user-images.githubusercontent.com/59040881/134837090-9c1ff776-06a5-4a15-a932-64e0c4144157.png)
As the screenshot shows, the current song is playing from a single release, and the auto play queue is enabled. The single just repeats over and over, and the auto queue isn't used.

**Comment by Alipoodle** [comment] 2024-02-05 16:22
Duplicate of #622

**Closed by Alipoodle** 2024-02-05 16:22 UTC
