### ISSUE TITLE
Add support for Ublock Origin

### ISSUE THREAD

**Issue by MKstudio-Tech** [ytmdesktop/ytmdesktop#1033] opened 2022-10-01 20:47 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Add support for Ublock Origin (or any other adblock that can block youtube ads).

**Comment by ReduxGB** [comment] 2022-10-02 03:02
To me this application is purely to make ytm a separate application with a few added features. An extension doesn't really fit into the purpose of the application, but I will say that you are free to add the feature yourself and if you so wish submit it as a PR for it to be looked at and possibly incorporated in the future.

**Comment by Alipoodle** [comment] 2022-10-02 13:27
We don't wish to add an AdBlock to YTM Desktop. >.<
There's a number of other Issues/FR been asking to add this, but we do not wish to add this to the "Core" build of it ourselves.
If an Extension system is made, (not natively included within the app) we'll allow users to make it and install it from that.
The only option is to make your own Fork of the application, include the Adblocker & Build it yourself. (I'm aware of a few forks, but unsure to if they're updated to the latest commits) OR (while annoying to say) Buy YouTube Premium.

Duplicate of #114

**Closed by Alipoodle** 2022-10-02 13:27 UTC
