### ISSUE TITLE
FR: response to multimedia computer keyboard play/stop/NEXT/PREV keys please.

### ISSUE THREAD

**Issue by fredphoesh** [ytmdesktop/ytmdesktop#230] opened 2020-07-07 19:20 UTC
Hey all,
I've just got a splendid new keyboard and noticed that the wonderful YTM app does not respond to these universal keys. All other apps I tried, VLC, Spotify etc work fine. The Google YT player does not work either by the way. It'd be nice though...
Cheers, be well,
Mark.

**Comment by adlerluiz** [comment] 2020-07-08 15:07
Hello, thanks for using ytmdesktop, what brand of keyboard? we have an issue of this same problem with the logitech keyboard

https://github.com/ytmdesktop/ytmdesktop/issues/100

**Comment by fredphoesh** [comment] 2020-07-08 19:21
Hi Luiz, yep, you are quite right, it is a Logitech keyboard... thanks for the response and for the lovely, enhanced software.

Mark.

**Comment by rickinbsb** [comment] 2020-07-11 16:01
I'm closing this as duplicate of #100, there is some discussion with solutions and workarounds there

**Closed by rickinbsb** 2020-07-11 16:01 UTC
