### ISSUE TITLE
<TITLE HERE>

### ISSUE THREAD

**Issue by hbstyle** [ytmdesktop/ytmdesktop#1148] opened 2023-08-30 16:06 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Don't play video always

**Comment by Alipoodle** [comment] 2023-08-30 19:13
Please provide more details in the next issue you add.
Duplicate of #46

**Closed by Alipoodle** 2023-08-30 19:13 UTC
