### ISSUE TITLE
YTM side bar appears after skipping any track

### ISSUE THREAD

**Issue by gcfrxbots** [ytmdesktop/ytmdesktop#961] opened 2022-05-06 03:04 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Whenever any track is skipped, a YTM sidebar appears for what seems like 1-2 frames then disappears, and seems to cause a slight lag between songs. Not sure if a 0.5-1s lag between skipping songs is related. No evident way to make the sidebar permanent, which would be preferable. 

### Expected Behavior

No popup appearing when skipping tracks.

### Steps To Reproduce

1. Play any music. 
2. Skip track
3. Observe the left side of the screen, just above the play/pause button. The youtube music sidebar will appear for just a moment.

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

10 Pro

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-05-07 15:38
Duplicate of #937

**Closed by Alipoodle** 2022-05-07 15:38 UTC
