### ISSUE TITLE
RAM usage grows indefinitely over time

### ISSUE THREAD

**Issue by RafalLauterbach** [ytmdesktop/ytmdesktop#892] opened 2022-01-13 10:32 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

App is using increasingly more RAM, I used it yesterday, got off my computer, and 1 day after it used 4GB of ram (after fresh start it uses <1GB)

I'm not sure if amount of RAM increased already yesterday ( and might be caused by playing songs from generated playlist, as it de-facto has more and more thumbnails to remember, to keep whole track-list )
or if RAM increased over night, but I suspect it might be first case and I suspect it might be because of auto-generated playlist?

I will keep observing and reporting in this thread. I already observed it few times in past, and just restarting app fixes RAM usage, but only until it gets big again.

### Expected Behavior

App should stay at steady level of RAM usage. 1GB is really most, I can agree to this app using.

### Steps To Reproduce

1. play auto-generated playlist for few hours (4-6?) (PPM song->start radio)
2. leave PC over-night (~10h, might be not required)
3. app uses now 4GB of ram (in my case)

### YTMDesktop

1.13.0

### OS

Ubuntu

### OS Version

20.04.3 LTS

### Arch

x64

### Installation way

Snapd

### Anything else?

There's no "help->about" section of toolbar, but config.json and ctrl+f "version" tells me, that :
"__internal__": { "migrations": { "version": "1.13.0" } },

so either I have that version? or I migrated from that version? Anyway, I'm putting is as version I'm using.
I'm using auto-update, so I would expect it to be newest stable version, but I've not confirmed that.

**Comment by Alipoodle** [comment] 2022-01-13 17:39
Duplicate of #249 
This is a YTM Issue at heart, and it is what is causing the high RAM usage in most cases.

Swapping between songs can easily show that RAM can increase rapidly.

**Closed by Alipoodle** 2022-01-13 17:39 UTC
