### ISSUE TITLE
sign-in yubikey 2FA gets stuck in infinite loading screen

### ISSUE THREAD

**Issue by JD1099** [ytmdesktop/ytmdesktop#616] opened 2021-02-11 04:48 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**

I use a [Yubikey](https://www.yubico.com/products/security-key/) for 2FA on my google account. The yubikey is used as the default 2FA method for first time logins. The sign-in process seems to get stuck right before it asks me to insert my key. (Normally the login process will tell me to insert the key when it is ready). I certainly don't know how to test my theory, but my hypothesis is the 2FA process gets stuck because the application/sign-in process can't get proper access to any usb ports.

**Note**: I was able to work around the issue by removing my yubikey from my google account for a moment.
Other 2FA methods work flawlessly. The only problem I have is with the yubikey.

 **To Reproduce**
 step 1: add a  [Yubikey](https://www.yubico.com/products/security-key/) to the 2FA methods in google account.
step 2: attempt to sign-in for the first time on ytmdesktop
 **Expected behavior**
 The sign-in process should ask me to insert my yubikey right after entering my password, but instead I get an infinite loading screen.

 **Screenshots**
What's supposed to happen:
 ![expected_bevahior_2FA](https://user-images.githubusercontent.com/58867565/107602361-d54e5080-6bee-11eb-84ad-766e3237fc78.png)

Expected outcome:
![Expected_behavior_2FA2](https://user-images.githubusercontent.com/58867565/107602360-d4b5ba00-6bee-11eb-8e09-9f49955e5284.png)
Gets stuck on this part:
![ytmdesktop_2FA_infi_wait](https://user-images.githubusercontent.com/58867565/107602362-d5e6e700-6bee-11eb-9621-b0cf0336ca88.png)

 **Environment:**
 * YTMDesktop version: v1.13.0
 * OS: ***Ubuntu linux***
 * OS version: ***5.8.0-41-generic***
 * Arch: ***64-bit***
 * Installation way: snapcraft

I hope this helps solve the issue. I tried my best to make a intelligent description. If you need more information lemme know!

**Comment by NovusTheory** [comment] 2021-02-11 21:34
I don't have a key myself, but I'm curious whether this works fine on other operating systems e.g. Windows and macOS. If anyone is able to provide that info it may help any contributors (like myself) see what the issue may be. I've done a lot of looking around and this issue seemed to have existed in GPMDP and was labeled as an upstream issue to Electron which makes sense this is more of a browser js API (Webauthn) that interacts with the native OS.

**Comment by rainydevbs** [comment] 2021-02-12 21:03
> 
> 
> I don't have a key myself, but I'm curious whether this works fine on other operating systems e.g. Windows and macOS. If anyone is able to provide that info it may help any contributors (like myself) see what the issue may be. I've done a lot of looking around and this issue seemed to have existed in GPMDP and was labeled as an upstream issue to Electron which makes sense since this is more of a browser js API (Webauthn) that interacts with the native OS.

Windows user here. Just downloaded YTMDesktop and the prompt for 2FA came right up. Inserted my Yubikey and was immediately authorized without any issues.

**Comment by kudlav** [comment] 2021-02-17 10:53
Using macOS 11 Big Sur and Yubikey 5 NFC. Everything works fine.

**Comment by gbalke** [comment] 2021-03-23 17:14
Same issue Ubuntu 20.04

**Comment by egelmex** [comment] 2021-04-13 07:14
Same issue in Ubuntu 20.10. In other apps the 2FA screen times out and gives the option of using another method if the stuck isn't inserted after a while, but I expect this is all under google's control.

**Comment by gbalke** [comment] 2021-04-13 08:45
I found that I could actually continue by inserting my yubikey and pressing it. The prompt is there just not rendered in the viewer.

**Comment by ChildishGiant** [comment] 2021-07-19 20:16
I'm having this issue on Ubuntu 18.04 but inserting my key and pressing it isn't working.

**Comment by gbalke** [comment] 2021-07-20 01:10
I found it to not reliably behave as I stated above. It would not register in most cases but once I got it to work, I kind of forgot about the issue. It never once appears though so I don't know how to reproduce it working vs not working.

**Comment by gladomat** [comment] 2021-08-30 07:58
Unfortunately, pressing the yubikey doesn't do it for me either on Ubuntu 20.04.

**Comment by jimmed** [comment] 2022-10-05 14:01
Just came across this issue in 2022 on PopOS 21.04 / YTMD v1.13.0.

This problem is specific to electron-based apps within snapcraft packages, as snap does not allow access to U2F devices (i.e. Yubikeys) without it being specified as a supported 'interface' within the snap package.

- [The `u2f-devices` interface](https://snapcraft.io/docs/u2f-devices-interface) on snapcraft docs.

### Workarounds:

- Wait a minute (or so) for the U2F prompt to timeout. After that, Google will present you with your alternative authentication options.
- If you're using 3rd party SSO which enforces the use of U2F, consider installing the YTMDesktop binary directly, instead of using snap.

**Comment by Alipoodle** [comment] 2024-02-05 16:05
Duplicate of #110

**Closed by Alipoodle** 2024-02-05 16:05 UTC
