### ISSUE TITLE
Innacurate Lyrics

### ISSUE THREAD

**Issue by greatwroth** [ytmdesktop/ytmdesktop#897] opened 2022-02-02 04:33 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I click the lyrics button on Monster by UNDREAM & IOVA it brings up the lyrics for either Monster by Lady Gaga if using Genius or Monster by Monster if using default Vagalume.

### Expected Behavior

When I click the lyrics button on Monster by UNDREAM & IOVA it should bring up the lyrics for Monster by UNDREAM & IOVA.

### Steps To Reproduce

1. Start listening to Monster by UNDREAM & IOVA
2. Click the lyrics button

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

setup .exe

### Anything else?

I've checked and both services have the correct lyrics entry and it is easily found by searching song title and artist. This is the only instance I have personally run into.

**Comment by Alipoodle** [comment] 2022-02-06 19:43
![image](https://user-images.githubusercontent.com/17199186/152698343-884f9620-2020-42b5-b45d-6ae7fc63cbb4.png)
![image](https://user-images.githubusercontent.com/17199186/152698381-2f6f3cec-5657-4673-b3a0-7f405a778a92.png)

Unable to reproduce this issue on both the official song, and even on a Video upload.
The Lyrics Finder isn't 100% perfect, there are chances that it will fail. to investigate it for specific instances aren't going to be much help towards the problems that might exist for it.

**Comment by greatwroth** [comment] 2022-02-15 21:59
Is there anything I should do to try to get different results (clear cache/settings) or is this just the state of the lyrics finder? Credit where credit is due it works ~99% of the time.

**Comment by Hershey025** [comment] 2022-02-17 12:28
> ![image](https://user-images.githubusercontent.com/17199186/152698343-884f9620-2020-42b5-b45d-6ae7fc63cbb4.png) ![image](https://user-images.githubusercontent.com/17199186/152698381-2f6f3cec-5657-4673-b3a0-7f405a778a92.png)
Can you tell the code of the theme that you are using for ytm desktop in this image?

**Comment by Alipoodle** [comment] 2024-02-02 12:39
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

This is more of an issue with 3rd party providers and Lyrics are currently not included in v2

**Closed by Alipoodle** 2024-02-02 12:39 UTC
Labels: Bug, YTMD V1
