### ISSUE TITLE
Please add option to disable double click full screen

### ISSUE THREAD

**Issue by harsh251004** [ytmdesktop/ytmdesktop#1231] opened 2024-01-06 17:31 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

HI THERE,
PLEASE ADD OPTION TO DISABLE DOUBLE CLICK FULL SCREEN WHEN PLAYING A SONG

### Solution

N/A

### Alternatives

N/A

### Anything else?

N/A

**Comment by Alipoodle** [comment] 2024-02-05 16:35
Duplicate of #935

**Closed by Alipoodle** 2024-02-05 16:35 UTC
