### ISSUE TITLE
<desktop application>

### ISSUE THREAD

**Issue by gurkankorkmaz1** [ytmdesktop/ytmdesktop#1011] opened 2022-07-28 08:23 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I want to download music via the desktop application.

**Comment by strugee** [comment] 2022-08-04 22:01
Duplicate of  #843

**Comment by Alipoodle** [comment] 2022-08-06 17:18
Duplicate of #843
Thanks @strugee

**Closed by Alipoodle** 2022-08-06 17:18 UTC
