### ISSUE TITLE
V2Rc4 Enable Speaker fill not working

### ISSUE THREAD

**Issue by Vexnass** [ytmdesktop/ytmdesktop#1181] opened 2023-10-15 22:16 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When enabled and restarted as requested, the subwoofer isn't working while the option is on. There's only sound coming out of my main 2 speakers. Am i just understanding the option wrong or is it not working as of right now?

### Expected Behavior

It should use all of your speakers not only the stereo ones.

### Steps To Reproduce

Settings
Playback
Enable Speaker Fill

### YTMDesktop

V2 RC4

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2023-10-15 22:29
Speaker Fill is implemented in the same way as in the v1.13 build, however it was an experimental API we enabled 😅
And may have since been removed in the newest versions of chromium/electron.

**Comment by Vexnass** [comment] 2023-10-15 23:35
That's weird tho as the option in the version you've mentioned never been a thing in my settings. That's why I was hopeful that V2 would bring that as it's quite crucial for me. In this case I'm gonna stick with the channel copy method then, until (if ever) this will be working once again :/

**Comment by Alipoodle** [comment] 2023-10-16 13:49
This is 1.14 and not 1.13 (I edited it strange after I realised my mistake)

Speaker Fill is done via added a flag to the electron app on start up. This was copied from Google Play Music Desktop player and worked in 1.14 to the user who tested it with me!

If Chromium has changed this flag or removed it, I'm happy to adjust what I need to do, however I have no way of testing this myself.


What settings do you use in Chrome to adjust for Speaker Fill?

**Comment by Vexnass** [comment] 2023-10-16 20:44
Im not using anything browser flag related. Im using APO's Equalizer to copy right and left channel to subwoofer. Couldn't find anything related to flags for Opera GX as its my main driver

**Comment by Alipoodle** [comment] 2023-10-18 08:57
😅 We apply the browser flag to enable the thing and that's it.
The flag we use is `try-supported-channel-layouts`
The discussion regarding the adding of this feature is #814 and describes the usage of it from GPMDP and the indivdual who was testing it confirmed it was working.

Some people suggest that using these 3 commands (includes the one I have) to a Chrome window gives the 5.1 support.
![image](https://github.com/ytmdesktop/ytmdesktop/assets/17199186/6a05b735-f888-4e3d-8927-437297a1532e)


Otherwise I cannot really say much else towards your setup and how that works and might mess up how we currently use for the system.

if you start YouTube Music Desktop app with the extra 2 flags `YouTube Music Desktop App.exe -Flag1 -flag2 and see if that works, then I can include the other 2 flags suggested

**Comment by Vexnass** [comment] 2023-10-18 23:03
Tried all three of them previously. Force wave audio only makes audio "stutter" and rest doesnt do anything at all. Well gotta wait and see if Google adds anything in the future

**Comment by Alipoodle** [comment] 2024-02-05 16:32
Closing this issue as this is the most we wil do for Surround sound ourselves.
Google / YTM will have to be the ones to decide on doing more.

**Closed by Alipoodle** 2024-02-05 16:32 UTC
Labels: Bug, More Info Needed
