### ISSUE TITLE
Default volume keyboard shortcuts break basic Windows functionality

### ISSUE THREAD

**Issue by AlexHimself** [ytmdesktop/ytmdesktop#912] opened 2022-02-19 01:48 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

The default **volume** keyboard shortcuts break standard Windows functionality. These specific shortcut keys are fundamental to Windows for basic text selection across all applications. It's similar to hijacking `Shift`+`<arrow key>`.

Generally, changing shortcut keys would be considered a feature request, but these specific shortcut keys are core to nearly every application that deals with text, I'd consider it a bug.

- `Ctrl`+`Shift`+`<Up Arrow>`
- `Ctrl`+`Shift`+`<Down Arrow>`

I've had issues using Microsoft Excel/Word/Office/Notepad/etc and it took a little while to figure out _why_ the most basic functions were broken.

### Expected Behavior

- `Ctrl`+`Shift`+`<Up Arrow>` - Should select all text in the upward direction until a break
- `Ctrl`+`Shift`+`<Down Arrow>` - Should select all text in the downward direction until a break

### Steps To Reproduce

1. Open a multi-line text application or multi-row Excel file
2. Place cursor in a location in the middle of the text or Excel file
3. Press `Ctrl`+`Shift`+`<Up/Down Arrow>`
4. [Bug] Cursor does not move and text is not selected

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-02-19 11:52
Shortcut can be changed and is possible for you to disable within the Settings Menu.
This does not seem like something which we need to change as this is just a Default value we set. 

I personally use CTRL + ALT + A (down) / Q (up)

**Comment by AlexHimself** [comment] 2022-02-19 21:51
I eventually found the shortcut, but it might take your average user a _long_ time to identify that application as the cause of apparent, broken system functionality.

I suppose it's up to you guys as the developers/maintainers. I'd just suggest a different default key binding.

I work in software in the business world and nearly every business-user I've dealt with is taught `Ctrl`+`Shift`+`<arrow>` because the arrow keys are intuitive and obvious for them.

**Comment by AlexHimself** [comment] 2022-05-18 16:18
**This is a bug**

**Comment by Alipoodle** [comment] 2022-05-20 11:19
@AlexHimself This is not a bug... The feature can be disabled by the user or recongifured to whatever they want, and is functioning 100% as intended [Pressing a keybind and an action happening]

The usage of the default keybind is indeed a bit more of an oversight by whoever originally decided on it. I will consider removing the default Keybinds for the applicaiton on Setup (besides media keys, as this is a music app) and to prevent this and other issues being accidentally triggered for users overall for other applications.

But to be clear
### You can Disable and Reconfigure the Keybind to what you want.
But I agree it's unclear that YTMD is the Cause of overriding it.

**Comment by M2ast** [comment] 2022-05-20 11:51
@Alipoodle Great stuff! If this default binding is removed then I believe this issue would be resolved.

**Comment by DorCoMaNdO** [comment] 2022-05-29 10:38
> I will consider removing the default Keybinds for the applicaiton on Setup

While I do agree the behavior is not a bug, if you are going to be removing keybinds to workaround this issue, I would also suggest removing the default "dislike" keybind to workaround another - WASD, Ctrl and Shift are used by most games, some games will require the use of both Shift and Ctrl and when moving to the right (D), while YTM is running that causes the currently playing song to be disliked and skipped, happened to me a couple of times before I remembered the keybind existed.

**Comment by Alipoodle** [comment] 2022-05-29 10:41
> I will consider removing the default Keybinds for the applicaiton on Setup (besides media keys, as this is a music app)
 
This was my intention to do ALL keybinds this would ultimately prevent the problem across any application.

**Comment by Afoulky** [comment] 2022-07-07 07:53
> **This is a bug**

"It's not a bug, it's a feature"

**Comment by lolmaus** [comment] 2022-09-29 10:18
It also hijacks <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>M</kbd> even after disabling all hotkeys in the Settings UI. 😡

**Comment by Alipoodle** [comment] 2024-02-02 13:29
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

Keybinds are blanked out within the YTMDv2, so this issue is now solved.

**Closed by Alipoodle** 2024-02-02 13:29 UTC
Labels: Enhancement, Good first issue/feature, YTMD V1
