### ISSUE TITLE
Allow Ublock Origin (or AdBlock) support

### ISSUE THREAD

**Issue by roysubs** [ytmdesktop/ytmdesktop#1042] opened 2022-10-22 10:04 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Can you add a setting that will allow Ublock Origin or AdBlock to handle/remove adverts please (if this support is already built-in, can you say where, as I could not see it)?

### Solution

Checkbox to enable Ublock Origin, or, for something more stealth, hidden option to place a file beside the executable that activates this option.

### Anything else?

The app is great, but becomes useless without Ublock Origin support as it would obviously be more pleasant for anyone to just go to YouTube on a browser (with Ublock Origin) and use there to avoid advert pollution when listening to music.

**Comment by Alipoodle** [comment] 2022-10-22 12:09
Duplicate of #114

**Closed by Alipoodle** 2022-10-22 12:09 UTC
