### ISSUE TITLE
How to prevent Videos from playing?

### ISSUE THREAD

**Issue by bruno-brant** [ytmdesktop/ytmdesktop#1056] opened 2022-12-05 12:50 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Make sure that the player only picks non-video tracks to play. 

Video tracks many times have worse audio quality than non-video ones, and for those of us (most?) who are using YTM as an audio player there's no benefit in playing the video version. 

### Solution

An option switch that would automatically enforce the player to always play in "song mode" instead of preferring videos. The switch already exists, but on any new song we can get back to playing videos:

![image](https://user-images.githubusercontent.com/1890900/205641163-e0f49152-07f1-4a36-8990-01775633b596.png)

**Comment by gabuch2** [comment] 2022-12-07 23:22
A solution to this would be appreciated. For example, the song _Romance no Kamisama_ no matter what I do it keeps playing the [video](https://music.youtube.com/watch?v=AgfUewgwPOw) instead of the [song](https://music.youtube.com/watch?v=LlhNOMa51Uw) in playlists. (Which is inconvenient because the video is the short version of the song and the audio quality is way lower)

**Comment by Alipoodle** [comment] 2023-02-11 20:47
This is a feature of YTM Premium. I have added a basic implementation into 1.14.2.

**Comment by bruno-brant** [comment] 2023-02-12 00:11
What you implemented controls when the stream switches to a video? Or is it just something decided on the server side?

Or could you point me to the right source so I can take a look?

**Comment by Alipoodle** [comment] 2024-02-04 18:23
Duplicate of #46 / Get YTM Premium

**Closed by Alipoodle** 2024-02-04 18:23 UTC
