### ISSUE TITLE
"Couldn't sign you in"

### ISSUE THREAD

**Issue by JanoutV** [ytmdesktop/ytmdesktop#878] opened 2021-12-03 09:27 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://user-images.githubusercontent.com/44194415/144578572-7fddb8eb-f458-41ed-a65c-002a489a43ba.png)

### Expected Behavior

I would like to login to my account to access my playlists.

### Steps To Reproduce

Open the app and try to log in

### YTMDesktop

v1.13.0

### OS

Red Hat Enterprise Linux

### OS Version

8.4

### Arch

x64

### Installation way

flathub

**Comment by ThPch** [comment] 2021-12-03 14:54
I have the same problem, any fix ?

**Comment by jadeezomg** [comment] 2021-12-03 17:07
Also encountered the same problem, on my first time install on Win10.

**Comment by YaddyVirus** [comment] 2021-12-03 19:32
Same issue here. Enabling less secure apps in Google account settings doesn't fix the problem.

**Comment by YaddyVirus** [comment] 2021-12-03 19:43
**Update:** Downloaded the 1.14.1 nightly build, tried signing in, failed the first two times, succeeded the third time.

**Comment by ThPch** [comment] 2021-12-03 20:01
It's crazy but it worked after the 4th or 5th time for me

**Comment by Alipoodle** [comment] 2021-12-03 20:19
Closing due to dupe of: #866

**Closed by Alipoodle** 2021-12-03 20:19 UTC
