### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by TimTrayler** [ytmdesktop/ytmdesktop#762] opened 2021-07-05 16:05 UTC
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Hey, while you can download, edit and rebuild ytmdesktop, some sort of plugin support would be amazing.

**Describe the solution you'd like**
Maybe a folder where you can put plugins inside. A plugin should be able to access the current page and have different events like on music change.

**Comment by adlerluiz** [comment] 2021-07-09 17:20
Hello,

Support for extensions and themes is already under development, and will soon be available in a final version

**Comment by seahindeniz** [comment] 2021-07-24 10:14
This probably related to #114, and support for extension mentioned over there as well

**Comment by Alipoodle** [comment] 2024-02-05 16:19
Duplicate of #592

**Closed by Alipoodle** 2024-02-05 16:19 UTC
