### ISSUE TITLE
Snap package constantly asks for permission to change default-url-scheme-handler subproperty despite already giving it permssion

### ISSUE THREAD

**Issue by thatLeaflet** [ytmdesktop/ytmdesktop#972] opened 2022-05-28 01:00 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Whenever I reopen ytmdesktop, I get this popup asking if I want to change the default-url-scheme handler. This makes sense for the first ever launch, however this keeps happening on each subsequent launch, which is unnecessary. When looking in Ubuntu's settings, it already has permission for ytmd:// links set.
![Screenshot from 2022-05-27 20-53-09](https://user-images.githubusercontent.com/80165419/170803384-8303ea26-52a6-4bd5-b345-627fa34f18fd.png)
 

### Expected Behavior

This popup would show up on the first ever launch of the app, but never again.

### Steps To Reproduce

1. Install Snap of ytmdesktop
2. Launch app, popup appears, click yes
3. Close app completely
4. Launch app again, popup appears again

### YTMDesktop

v1.13.0

### OS

Linux

### OS Version

Ubuntu 22.04

### Arch

x64

### Installation way

snapcraft

**Comment by Alipoodle** [comment] 2022-05-28 12:22
Dupe of #630 
This is fixed in 1.14.1 Pre-release and above.

**Closed by Alipoodle** 2022-05-28 12:22 UTC
