### ISSUE TITLE
GUI Missing

### ISSUE THREAD

**Issue by mountswolmore** [ytmdesktop/ytmdesktop#1136] opened 2023-07-22 13:17 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Opening app doesn't open the app. It starts running but the window doesn't show up on the screen. Mousing over the icon shows the preview. 

Tried force closing and reinstalling. Just started after a reboot when it was previously working.

Due to changes to Windows 11, I can't right click and Move the window to see if it's off screen.

### Expected Behavior

The program should be visible when opening. 

### Steps To Reproduce

Launch program.

### YTMDesktop

latest

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2023-07-23 13:48
Duplicate of #918

**Closed by Alipoodle** 2023-07-23 13:48 UTC
