### ISSUE TITLE
lyric follower

### ISSUE THREAD

**Issue by Antexous** [ytmdesktop/ytmdesktop#1185] opened 2023-10-18 02:18 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

the thing where it follows lyrics

### Solution

the thing where it follows lyrics

### Alternatives

the thing where it follows lyrics

### Anything else?

the thing where it follows lyrics

**Comment by roighteously** [comment] 2023-10-18 03:26
is this the thing where it follows lyrics?

**Comment by Alipoodle** [comment] 2023-10-18 08:48
Duplicate of #809

**Closed by Alipoodle** 2023-10-18 08:48 UTC
