### ISSUE TITLE
Window Stuck Off-Screen after Disconnecting Second Display

### ISSUE THREAD

**Issue by fortisconsulting** [ytmdesktop/ytmdesktop#1015] opened 2022-08-06 21:14 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

First off, I LOVE your application!  Thanks for doing what Google & YT don't care to offer their communities!

Using Windows 11, I will have YTMDesktop open on another display/second monitor. After disconnecting the monitor from my laptop, YTMDesktop remains open, BUT it is stuck "off-screen" and cannot be accessed. I click the icon in the task-bar, but it does not appear no matter what I do.

Various recommended solutions for Windows to bring an off-screen window back on-screen don't work:  trying to move it with windows key + arrow key, changing screen resolution, alt + tab. None works.

Even quitting the application entirely and restarting doesn't work. The only known solution is to reboot my computer, which is time-consuming for a media player alone.

P.S. Here are my Appearance settings for reference. I prefer to have it running in the background. On close (x), the app stays open, accessible via taskbar icon.
![Screenshot 2022-08-06 160637](https://user-images.githubusercontent.com/96495652/183266031-edff51d4-2ac9-4487-ba2c-706253b7ffd6.png)
 

### Expected Behavior

Regardless of which of my displays YTMDesktop is on, after disconnecting a second display, I desire for YTMDesktop to be accessible from my main display.

### Steps To Reproduce

See current behavior above.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-08-07 13:49
Duplicate of #918

Can be fixed by:
- Hitting `Win+D` twice
- Manually editing the X/Y location of the window in the `%appdata%/youtube-music-desktop-app/config.json` file.

**Closed by Alipoodle** 2022-08-07 13:49 UTC

**Comment by fortisconsulting** [comment] 2022-08-10 16:21
Thank you!

Eric Teachout, CSM
Owner & Project Manager

Fortis Agilis Consulting
Courage & Agility for Your Strategic Initiatives

Project Management  |  Digital Marketing  |  E-Learning & Communications
Schedule a Meeting with Me<https://calendly.com/fortisagilis>

On 8/7/2022 8:49:37 AM, Alipoodle ***@***.***> wrote:

Duplicate of #918<https://github.com/ytmdesktop/ytmdesktop/issues/918>

Can be fixed by:

  *   Hitting Win+D twice
  *   Manually editing the X/Y location of the window in the %appdata%/youtube-music-desktop-app/config.json file.
