### ISSUE TITLE
Can't use SIGN IN button

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#432] opened 2020-10-06 13:32 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Today I changed my Google password; YTMD is now signed off, but I CAN'T use the sign in button, it just does not react to my clicks.

**To Reproduce**
1. Change Google password
2. open YTMD
3. click SIGN IN button

**Expected behavior**
Sign in form to appear

**Screenshots**
N/A

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by pdario** [comment] 2020-10-06 14:08
Hey!

I "enabled Windows 10 media service" and added "show track informatio [...]" and then tried again by chance: it worked!!

**Comment by superbonaci** [comment] 2021-08-24 10:28
What happens if you remove all ytmdesktop data? Try a clean install.

**Comment by uygary** [comment] 2022-01-03 04:38
Duplicate of #432.

**Comment by uygary** [comment] 2022-01-03 04:41
Duplicate of #772.

**Comment by uygary** [comment] 2022-01-03 04:49
This issue still exists.
Is there a way to open up developer console to see what's going on behind the scenes?

**Comment by uygary** [comment] 2022-01-03 04:51
> What happens if you remove all ytmdesktop data? Try a clean install.

I didn't try uninstalling it, but I tried it on a separate PC, and I had the same issue there as well.

**Comment by Alipoodle** [comment] 2022-01-03 20:20
It's recommended to delete the folder if you are going for a FULL clean install:
  `%appdata%/youtube-music-desktop-app`

Otherwise, the newest version (1.14.1) seem to mitigate this issue from my experience.
Although does not guarantee a perfect fix, the "Unsafe browser" still happens every so often and is the pinned issue currently.

**Comment by uygary** [comment] 2022-01-03 20:23
The separate PC I mentioned wasn't a reinstall, but a first time installation.
That being said, if 1.14.1 seems to fix the issue, I guess I'll just wait for the release to come out.
In the meantime, figuring out how to enable the developer console could still help.

**Comment by Alipoodle** [comment] 2024-01-29 10:25
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:25 UTC
Labels: Bug, YTMD V1
