### ISSUE TITLE
Remote control server doesn't connect

### ISSUE THREAD

**Issue by Davies-Owen** [ytmdesktop/ytmdesktop#476] opened 2020-10-29 03:48 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Describe the bug**
When I click 'Remote control' in the integrations section of the settings, it redirects me to http://localhost:9863/, but I get a message saying "This site can’t be reached - localhost refused to connect."

**To Reproduce**
1. Click 'Remote control' in the integrations section of the settings.
3. See error

**Expected behavior**
I expected some sort of remote control set-up page to appear.

**Screenshots**
![image](https://user-images.githubusercontent.com/51712306/97523153-834f2b00-196f-11eb-9656-9ef5c04b0ff2.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Windows***
 * OS version: ***10***
 * Arch: ***x64***
* Installation way: ***.exe***

**Comment by Davies-Owen** [comment] 2020-10-29 13:56
I'm also experiencing this issue on Ubuntu 20.04.

**Comment by adlerluiz** [comment] 2020-11-03 17:06
the first time the server is started, it asks for permission to run the server, did it appear to you? would you be able to check if this port is being listened when starting YTMDesktop ??

**Comment by Davies-Owen** [comment] 2020-11-03 17:13
No permission window appears, and no process is listening on port 9863.

**Comment by TheHippo** [comment] 2020-12-30 07:55
Same here, but I'm on Ubuntu.

**Comment by florindediu** [comment] 2021-03-09 13:07
I have the same problem on iMac.

**Comment by vvume** [comment] 2021-10-03 15:02
I have the same problem. I get this error when turning on the remote setting:
![image](https://user-images.githubusercontent.com/30203439/135759775-a323e9a0-18fe-4c51-b292-4dc85b71a8ff.png)

**Comment by eltharynd** [comment] 2022-02-03 02:37
Same here on Win11.. 
It used to work as intended till not long ago then it stopped for some reason.
I noticed there's a bunch of different issues that seem to be linked to the same issue.

For some reason the socket doesn't start. Even the stream deck YTMD connector fails, so does an app I developed myself to show playing track on screen.

I tried downloading the repo to debug it but it fails on npm install... 
Might try to build it again tomorrow

**Comment by eltharynd** [comment] 2022-02-03 03:35
> I have the same problem. I get this error when turning on the remote setting. I checked to make sure that there weren't any other applications on that port. I even tried running the app as administrator, but something seems to be blocking it from binding on Windows 10. ![image](https://user-images.githubusercontent.com/30203439/135759775-a323e9a0-18fe-4c51-b292-4dc85b71a8ff.png)

This is unrelated. Sometimes when the app crashes the node process keeps running in the background.
To fix this close YTMD -> open task manager -> look for any node applications and kill them -> restart YTMD

**Comment by Alipoodle** [comment] 2024-01-29 10:26
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:26 UTC
Labels: Bug, YTMD V1
