### ISSUE TITLE
Media Keys not working on Mac Catalina

### ISSUE THREAD

**Issue by donovan96** [ytmdesktop/ytmdesktop#382] opened 2020-09-12 19:31 UTC
- [1 ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ 1] I verified that there is no open issue for the same subject.

**Describe the bug**
The media keys isn't working on Mac OS Catalina (10.15.6) but it is working on my older 2011 MBP running High Sierra (10.13.6)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1***
 * OS: ***Mac***
 * OS version: ***10.15.6***
* Installation way: ***brew via terminal***

**Comment by Dukestep** [comment] 2020-09-14 11:23
Duplicate of #205.

**Closed** 2020-09-15 22:51 UTC
