### ISSUE TITLE
Error when closing program

### ISSUE THREAD

**Issue by SandrKH** [ytmdesktop/ytmdesktop#970] opened 2022-05-22 19:08 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Имя сбойного приложения: YouTube Music Desktop App.exe, версия: 1.13.0.0, метка времени: 0x5f4dbeb4
Имя сбойного модуля: ntdll.dll, версия: 10.0.19041.1682, метка времени: 0x7b5414ec
Код исключения: 0xc0000374
Смещение ошибки: 0x00000000000ff249
Идентификатор сбойного процесса: 0x24f4
Время запуска сбойного приложения: 0x01d86e0d9154055a
Путь сбойного приложения: C:\Users\Sandr\AppData\Local\Programs\youtube-music-desktop-app\YouTube Music Desktop App.exe
Путь сбойного модуля: C:\Windows\SYSTEM32\ntdll.dll
Идентификатор отчета: f775634f-1829-489b-99c2-caa9d23dab72
Полное имя сбойного пакета: 
Код приложения, связанного со сбойным пакетом: 

### Expected Behavior

*

### Steps To Reproduce

1. open programm
2. close programm

### YTMDesktop

1,13

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

YouTube-Music-Desktop-App-Setup-1.13.0.exe

**Comment by Alipoodle** [comment] 2022-05-22 19:58
This is a direct Duplicate of #931 regarding it throwing up errors and this is nothing that we directly are doing for it.

To repeat from before:
> It has nothing directly to do with us and likely a problem within Electron itself. (Reviewing their GitHub this has been a reported issue back in v1.7.4, We're on V11)
> Going through my Logs in Event Viewer, I've seen Adobe Software causing this same error, and 0 entries of YouTube Music Desktop erroring with this.
>
> Considering this is an issue which is only displayed within Event Viewer and not publicly to the user, This issue is also visible within other programs, and we are not do anything ourselves with DLLs like this.
> I do not see this as an issue for YTM Desktop.
>
> I will leave this open for a short while for a comment, however I do not see this changing my mind

**Closed by Alipoodle** 2022-05-22 19:58 UTC
