### ISSUE TITLE
Main window opens partially off screen on 2nd monitor

### ISSUE THREAD

**Issue by PopeHensterIX** [ytmdesktop/ytmdesktop#922] opened 2022-03-09 05:11 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Main window opens partially off screen when both conditions are true:
- opening on monitor 2 and monitor 2 scaling is different from monitor 1 
- Monitor 2 is located above monitor 1.

### Expected Behavior

Window should reopen in the same location where the window was previously closed.

### Steps To Reproduce

1. Set monitor 1 scaling to 125% in windows.
2. Set monitor 2 scaling to 100% in windows.
3. Have monitor 2 position above monitor 1
4. Put main window on monitor 2
5. Close the application
6. Open the application

### YTMDesktop

v1.14.1

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

.exe

### Anything else?

It appears the offset used to put the window back where it is supposed to be is being broken by windows scaling. Turning off the scaling seems to remove the issue. Putting the monitors side by side may also produce this issue but i have not tested this.
This also appears to be an issue in v1.13.0

**Comment by Alipoodle** [comment] 2022-03-09 08:45
Ironically this is my setup at work and using my 16:10 1080p laptop at the bottom and 4k on top (125%) and not having issues here personally.

Ironically Windows Scaling + Electrons sizing/position are reported incorrectly or Win Scaling tweaks it later causing a bunch of issues and without checking if said monitor has scaling (don't think this is natively part of Electron to check) this might just be an issue which is left untouched for a while

1.14.1 has got some additional logic within it to try and make sure that the windows position is at least visible and not hiding off the screen.

**Comment by PopeHensterIX** [comment] 2022-03-09 23:13
Extra info
My monitor resolutions are 2560x1080 on top monitor and 2560x1440 on the bottom one.
This aspect ratio difference may also be an additional factor in this issue

**Comment by Deav-91** [comment] 2022-06-06 19:47
Same issue on 1.14.2 (PATCHED).
Main monitor is 4K (3840x2160), secondary screen (to the _left_ is 2K (2160x1440)
Scaling on main monitor is 125%, secondary is 100%

**Comment by milesbuckton** [comment] 2022-06-20 12:02
I had the same problem with versions `1.13.0` - `1.14.2`. My issue was working with dual monitors, and the window would go off of the screen for some strange reason. I resolved it by switching to either one monitor, or changing to a higher resolution than what it was set to originally.

I reset the `window-position`, and `miniplayer-position` coordinates to `0` in the `%appdata%/youtube-music-desktop-app\config.json` file. This resolved my reoccuring issue! 👏🏻 

```JSON
	"window-position": {
		"x": 0,
		"y": 0
	},
		"miniplayer-position": {
		"x": 0,
		"y": 0
	},
```

**Comment by 05-1** [comment] 2022-06-28 21:38
> 

you are a gigachad, this helped fix it being off screen for me as well.

my main monitor was 4k, scaled at 150 and my second one was 1080p scaled at 100. the 1080p one was on the left and abt the same size

**Comment by Alipoodle** [comment] 2022-08-07 13:52
Duplicate of #918

Can be fixed by:
- Hitting `Win+D` twice
- Manually editing the X/Y location of the window in the `%appdata%/youtube-music-desktop-app/config.json` file.

**Closed by Alipoodle** 2022-08-07 13:52 UTC
