### ISSUE TITLE
Application opens on a screen which doesn't exist

### ISSUE THREAD

**Issue by ctyldsley** [ytmdesktop/ytmdesktop#1107] opened 2023-03-31 09:23 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I use YTMDesktop on a laptop which is often plugged into a second screen and moves between offices etc. Whenever I open the YTMDesktop app it now appears to open on a screen which doesnt exist. If I shift+right click there's no options appear to move the window. The app is simply unreachable and therefore unusable on my laptop currently. Reinstalling doesn't seem to solve.

I had this issue with a previous laptop, but just used a web browser instead for a few weeks. However now with my new device after a few weeks of owning it and YTMDesktop having no issues, suddenly the app is doing the exact same behaviour.

When I open and close the app on the taskbar I can see the window animate as if it's going towards a third screen which doesn't exist. Unplugging the screen or changing second screen options in Windows makes no difference. It's as if the app is displaitself to display on a non-existent screen.

Windows 11
Latest version of YTMDesktop

### Expected Behavior

Application should open on visible screen.

### Steps To Reproduce

Unknown

Use the app across multiple screens, disconnect those screens, place laptop into sleep whilst YTMDesktop on another screen for example.

### YTMDesktop

1.13.0

### OS

Windows

### OS Version

11

### Arch

x86

### Installation way

exe

**Comment by salleq** [comment] 2023-04-02 19:10
I have the same issue but managed to resume using the app by deleting all settings of the app from %appdata%\youtube-music-desktop-app

Next time this happens I might check which file contains the window position.

**Comment by paulpugh000** [comment] 2023-04-13 22:57
I also managed to get over the hurdle (after trying to reinstall) by manually wiping the `\Roaming\youtube-music-desktop-app` folder

**Comment by BaxBoyGH** [comment] 2023-04-14 20:17
Had the same issue
By deleting the folder and reinstalling fixed it for me. ;)

**Comment by guillaumetousignant** [comment] 2023-04-18 14:17
In the `\Roaming\youtube-music-desktop-app` folder, there is a `config.json` file. In it, there is a `window-position` configuration item, with `x` and `y` under it. When the issue happened, mine were set to garbage values. Closing the app, setting both `x` and `y` to `0`, and opening the app again fixed the issue for me. No need to reinstall or anything.

**Comment by KirylMi** [comment] 2023-05-17 13:24
> 

This fixes the issue. Confirmed.

**Comment by Alipoodle** [comment] 2023-07-23 14:10
Duplicate of #918

**Closed by Alipoodle** 2023-07-23 14:10 UTC
