### ISSUE TITLE
Switch to "song only" instead of "video"

### ISSUE THREAD

**Issue by pdario** [ytmdesktop/ytmdesktop#871] opened 2021-11-18 15:33 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

On my mobile I see I can switch between "song only" and "video"; is it possible to make is so with YTMD?

**Comment by Alipoodle** [comment] 2021-11-18 17:00
This is a premium feature which seems to slowly being released.

**Comment by Placeholder6** [comment] 2021-11-25 16:38
> This is a premium feature which seems to slowly being released.

that option is actually available for every premium user on phone, however no such thing exists on the web client

**Comment by Alipoodle** [comment] 2021-11-26 11:50
This is not true.
It does exist in the Desktop Client, but as Stated it seems to be rolling out slowly.

This can be found with the UI of YT Music, however this is kinda of a scam.
![image](https://user-images.githubusercontent.com/17199186/143576470-5824cd70-c2d1-468d-81cb-ea512db13b1c.png)

This is enabling it, however setting it to "song" mode will only toggle the video to not disable, but will still fetch the video in the background. 😓  Not really the solution we are looking for.
(This maybe due to me being a Free User)

**Comment by Alipoodle** [comment] 2021-11-26 11:51
Closing issue due to duplicate of #46

**Closed by Alipoodle** 2021-11-26 11:51 UTC

**Comment by speedstyle** [comment] 2022-02-03 14:09
@Alipoodle This is not a duplicate of #46.

Song mode switches between two separate video IDs, such as https://music.youtube.com/watch?v=xpVfcZ0ZcFM and https://music.youtube.com/watch?v=FrsOnNxIrg8. By default the [artist page](https://music.youtube.com/channel/UCU6cE7pdJPc6DU2jSrKEsdQ) shows the songs, the [album page](https://music.youtube.com/playlist?list=OLAK5uy_lKouR3b3iarfXfc31uj52NU9wcVKfZ5Yg) shows the music videos, search results show both.

With Premium, song mode shows the pure songs in the album instead. Sponsorblock and disabled video go some way to making the video seem like the song, but aren't as good. It's possible to get this information, as e.g. giving the album URL to youtube-dl fetches the songs and not the videos.

**Comment by Alipoodle** [comment] 2022-02-03 14:21
This wouldn't be the ideal way of doing this in any way, they would be entirely separate streams and can entirely mess up when users switch between them.
As suggested by the user:
> On my mobile I see I can switch between "song only" and "video"
This stops the Video stream of data and does not swap over to a different video.

Yes YTM has options for both a Music Version and a Video version, but in 50% of cases these are the exact same streams with just different "visual" front end and multiple YT Ids, as most people don't need a different "Music" video style.

**Comment by speedstyle** [comment] 2022-02-03 16:49
I believe the song mode he describes does switch to a different ID, as explained on the feature announcement https://blog.youtube/news-and-events/youtube-music-now-lets-listeners-switch/

> YouTube Music has perfectly time-matched over five million official music videos to their respective audio tracks … When you flip from video to song, say goodbye to the other sounds that go with the music video — like those long introductions — and enjoy the song as it was intended.

There are a very significant number of songs that have gaps in their music video, or e.g. Sponsorblock wouldn't have bothered to implement a category for them.

I'm not bothered about swapping like the official app during playback: as you say it would be difficult if even possible to reimplement downloading the cut times and transitioning between them. I was envisioning more of a setting to use the song IDs by default, so I could just click play on an album and listen to the songs.

At the moment I do it manually, searching and queuing the songs individually before removing the videos, but ytdl shows it's possible to get the songs quickly from the playlist link. I can try and write a plugin for this myself, but whatever else I really don't think it's duplicate functionality.

**Comment by Alipoodle** [comment] 2022-02-05 11:50
If you'd like to make this a PR to get it to work be my guest. 

But my problem lies at the getting this other ID without entirely reverse engineering the App and then implementing it in a feasible way where it's not ruining security of the users Google Account or being finicky to setup and replace existing YTM functionality (I.E. adding song to playlist, queue etc)
