### ISSUE TITLE
Add support for mac function key support

### ISSUE THREAD

**Issue by DavidZha1994** [ytmdesktop/ytmdesktop#958] opened 2022-04-30 14:46 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Add support for mac function key support

**Comment by roberto-filho** [comment] 2022-05-23 09:39
This was working for me with macOS Cataline (10.15).
Once I upgraded to Monterey (12.4) it stopped working.

**Comment by A-Matt** [comment] 2022-05-23 10:23
To my knowledge you need to Accessibility features for YTM Desktop for this to function.
Check more out in this thread: https://github.com/ytmdesktop/ytmdesktop/issues/376#issuecomment-1051847238

**Comment by DavidZha1994** [comment] 2022-05-24 12:38
Ive already enabled Accessibility features for YTM Desktop but this function is still not working. Im using Monterey 12.3.1 on a MacBook Pro 16 2021

**Comment by roberto-filho** [comment] 2022-05-24 12:39
> (...) Is this worth adding a note to the Keybinds settings (possible with a link to open up that menu, if possible) to enable this Accessability Settings?

I think it is definitely worth adding a note about this. It is a common issue.
Although I enabled accessibility features and it still didn't work... so I think that is not the issue.

**Comment by miguelammatos** [comment] 2022-07-28 20:08
I can confirm this issue. Media keys do not work even with the Accessibility option enabled.
MacOs version: 12.3.1
YTM version: 1.13.0

**Comment by Alipoodle** [comment] 2022-08-07 14:00
As I'm not a Mac User 😅
This is going to be a tad bit of a problem for testing and will have to find someone else who is able to do some more testing to the issue / problem.

**Comment by squidbork** [comment] 2022-08-15 23:50
Seems like https://github.com/ytmdesktop/ytmdesktop/pull/767 would fix this, but that PR (and https://github.com/ytmdesktop/ytmdesktop/pull/637) have been untouched for a while

**Comment by Alipoodle** [comment] 2024-02-03 11:32
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-03 11:32 UTC
Labels: Bug, More Info Needed, YTMD V1
