### ISSUE TITLE
Window of YTM goes out of bounds in my desktop

### ISSUE THREAD

**Issue by StupitVoltMain** [ytmdesktop/ytmdesktop#1133] opened 2023-07-15 12:21 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Window goes out of bounds and I can't interract with app

### Expected Behavior

That window should appear within reaches of my desktop

### Steps To Reproduce

Download app
Open app

### YTMDesktop

1.13.0

### OS

Windows 

### OS Version

10

### Arch

x86

### Installation way

.exe

**Comment by Scootz1** [comment] 2023-07-18 11:23
Have you tried the "Temporary Fix" in [issue #826](https://github.com/ytmdesktop/ytmdesktop/issues/826)?

Latest Windows 11 update caused this issue for me. Fix worked for me.

**Comment by Alipoodle** [comment] 2023-07-23 13:52
Duplicate of #918

**Closed by Alipoodle** 2023-07-23 13:52 UTC
