### ISSUE TITLE
Make it compatible with modernflyouts

### ISSUE THREAD

**Issue by Sygmstr** [ytmdesktop/ytmdesktop#1091] opened 2023-02-12 21:32 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Make it so you can scrub threw music using modernflyouts for windows

**Comment by Alipoodle** [comment] 2023-02-12 22:04
Duplicate of #780

**Closed by Alipoodle** 2023-02-12 22:04 UTC
