### ISSUE TITLE
Can't sign in with google accout

### ISSUE THREAD

**Issue by hackerchickenYT** [ytmdesktop/ytmdesktop#990] opened 2022-07-01 00:40 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.
 -Problem every time i try to sign in google wont let me because its "unsafe".

**Comment by Alipoodle** [comment] 2022-07-01 04:32
Duplicate of #866

**Closed by Alipoodle** 2022-07-01 04:32 UTC
