### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by Dayvy11** [ytmdesktop/ytmdesktop#911] opened 2022-02-18 15:32 UTC
### Consent

- [ ] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When the app is set to running in background it causes javascript error when you try to open app from desktop or taskbar

![image](https://user-images.githubusercontent.com/97882827/154711620-fd4c33ed-4a03-483f-908e-a3d1ca4cc509.png)

### Expected Behavior

Expecting app to just show itself without this error window

### Steps To Reproduce

1. Make sure your YT Music app is set and running in background

![image](https://user-images.githubusercontent.com/97882827/154712052-93bb7a33-5694-4429-88f5-03c58990a768.png)

2. Run the app
3. Then error appears

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x86

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-02-19 21:45
This is happening because another application (likely another instant of YTM) is already running.
I believe to my knowledge this issue is already fixed in 1.14.1

Dupe of #464

**Closed by Alipoodle** 2022-02-19 21:45 UTC
