### ISSUE TITLE
No titlebar or close button in settings window.

### ISSUE THREAD

**Issue by Innarel** [ytmdesktop/ytmdesktop#291] opened 2020-08-05 21:09 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
When "disable titlebar" is enabled, it hides the titlebar also for settings window and custom theme edition window. So I can't close those windows.

 **Expected behavior**
Only the main windows titlebar must be hidden.

 **Screenshots** 
![image](https://user-images.githubusercontent.com/51493189/89464329-a7bbb280-d746-11ea-98f9-5b77bfd384b1.png)

 **Environment:**
 * YTMDesktop version: ***v1.12.0***
 * OS: ***win32***
 * OS version: ***10.0.18363***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by rickinbsb** [comment] 2020-08-07 06:45
This is actually the intended behaviour, all windows draw with the same title bar (except the miniplayer)

**Comment by kudlav** [comment] 2020-08-26 08:49
Hi, I see this as a bug not a feature as well. Because the main purpose of hiding title bar is to safe space. In popup windows it is irrelevant because they are not in full-screen anyway.

**Comment by cmcinroy** [comment] 2020-10-09 09:39
So, how to close popup windows?

**Comment by kudlav** [comment] 2020-10-09 11:48
Hi,
if you are Windows user, right click on task bar icon for popup and close
it. Or pressing ALT+F4. When using Mac I assume by CMD+W.

--
Vladan Kudláč

Dne pá 9. 10. 2020 11:40 uživatel Craig McInroy <notifications@github.com>
napsal:

**Comment by cmcinroy** [comment] 2020-10-09 13:37
Ah, yes... I'm using Linux. I had tried Esc, Ctrl-W, Cmd-W... turns out Alt-F4 works. 👍

**Comment by GallopingCow** [comment] 2020-10-26 20:41
I agree with the original poster. There should be some button or way to close the additional windows without having to know a keyboard shortcut. This is fine for power users, but perhaps at least the Escape button could also serve to close additional windows to make it more intuitive.

**Comment by rickinbsb** [comment] 2020-10-26 21:48
I think closing secondary windows with esc and adding a customizable hotkey to the main window would be a good solution to this

**Comment by Alipoodle** [comment] 2024-02-04 18:35
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-04 18:35 UTC
Labels: Bug
