### ISSUE TITLE
Cannot login to google

### ISSUE THREAD

**Issue by ItzShiro** [ytmdesktop/ytmdesktop#963] opened 2022-05-12 16:57 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

While wanting to login i cannot because google blocks ytd

### Expected Behavior

While trying to login google says that application may be dangerous 

### Steps To Reproduce

Just try to login

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-05-12 18:44
Duplicate of #866

**Closed by Alipoodle** 2022-05-12 18:44 UTC
