### ISSUE TITLE
proxy/vpn servers

### ISSUE THREAD

**Issue by h1z1z1h16584** [ytmdesktop/ytmdesktop#1163] opened 2023-09-17 23:07 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

can you add proxy feature because I want to use it when I travel and all it shows is "not available in your country"

**Comment by Alipoodle** [comment] 2023-09-17 23:10
Duplicate of #178

**Closed by Alipoodle** 2023-09-17 23:10 UTC
