### ISSUE TITLE
Can't Sign in

### ISSUE THREAD

**Issue by OrionNASA97** [ytmdesktop/ytmdesktop#919] opened 2022-03-05 21:22 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Click Sign in
Attempt to enter email to login to my YouTube Music account

![image](https://user-images.githubusercontent.com/45722792/156900202-cbe188e5-4b82-4a4d-8775-54edee785561.png)

Get this error "Couldn't sign you in This browser or app may not be secure"

### Expected Behavior

Allow me to log in 

### Steps To Reproduce

Go to "Sign-in"
Attempt to enter your account credentials

### YTMDesktop

v1.13

### OS

Windows 

### OS Version

11

### Arch

x64

### Installation way

.exe

### Anything else?

Someone else in a thread about this in November said that it might just be an outdated version of Firefox user agent this app uses, not sure if that's correct but it seems very plausible

**Comment by Alipoodle** [comment] 2022-03-05 21:28
This is still a Duplicate of #866 
There's no consistent way to get around this has been found.

**Closed by Alipoodle** 2022-03-05 21:28 UTC

**Comment by OrionNASA97** [comment] 2022-03-05 21:33
Thanks for replying, I fixed it by following that thread. v1.11.0 works just fine!
