### ISSUE TITLE
sponsorblock

### ISSUE THREAD

**Issue by senolfndk** [ytmdesktop/ytmdesktop#966] opened 2022-05-15 17:28 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Can you add ad blocking feature?

### Solution

sponsor block

**Comment by Alipoodle** [comment] 2022-05-15 18:09
Duplicate of #114

**Closed by Alipoodle** 2022-05-15 18:09 UTC
