### ISSUE TITLE
Make this compatible with Rainmeter

### ISSUE THREAD

**Issue by Colin11200** [ytmdesktop/ytmdesktop#317] opened 2020-08-13 22:06 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
No, but maybe for others. 

**Describe the solution you'd like**
So I have Rainmeter for my desktop, and the music player that I have for my desktop through them won't detect the music being played. For the artist and song name it just says "N/A" and shows nothing as playing. 

**Describe alternatives you've considered**
Maybe instead of throwing in Rainmeter support, just enable an option in the settings to play sound/music through a system default program, so other programs similar to Rainmeter may also detect the music that is being played through windows media player, or whatever program. 

I have attached 2 player files, just open them with notepad or whatever. These are from 2 different skins on Rainmeter, both integrating music player support and both being in the top 10 Rainmeter skins. Or at one point, anyway. Player1 is Mond, and Player is Senja. I think they have a different way of coding them, if it is anything like coding for the time widgets. 

[Player.zip](https://github.com/ytmdesktop/ytmdesktop/files/5071622/Player.zip)
[Player1.zip](https://github.com/ytmdesktop/ytmdesktop/files/5071627/Player1.zip)

**Additional context**
In the screenshot, Mond is the top player not detecting anything. Senja is the bottom. 
I have no idea if I could just add it myself or not, but if I could i have no idea how. Im no coder but I love this app and your loyalness to us!
![2020-08-13 16_04_22-NVIDIA GeForce Overlay](https://user-images.githubusercontent.com/69653313/90191769-b88baa00-dd7e-11ea-88ea-1b2868d0ebec.png)

**Comment by rickinbsb** [comment] 2020-08-14 00:17
I'll label this as bug, since rainmeter should be detecting the song already

**Comment by adlerluiz** [comment] 2020-08-15 02:12
this is not a bug, is that for now the integration is only done with WebNowPlaying and from what I saw, these other plugins do not use it, I will study how to integrate with other rainmeter services

**Comment by Alipoodle** [comment] 2021-11-11 17:23
Closing this issue as we support WebNowPlaying (The standard for rainmeter) and cannot investigate more into the given Skins provided.

**Closed by Alipoodle** 2021-11-11 17:23 UTC
Labels: Enhancement, More Info Needed
