### ISSUE TITLE
request; cast

### ISSUE THREAD

**Issue by Tecko71** [ytmdesktop/ytmdesktop#113] opened 2020-03-08 11:20 UTC
Cast option for the windows app would be nice. Like there is now on the official app.

**Comment by rickinbsb** [comment] 2020-03-14 17:15
I'm closing this, as it is a duplicate of #29

**Closed by rickinbsb** 2020-03-14 17:15 UTC

**Comment by rickinbsb** [comment] 2021-04-01 00:54
> Just wondered if there is any update on the streaming function?

check #29
