### ISSUE TITLE
Settings won't load on Linux

### ISSUE THREAD

**Issue by euclidssss** [ytmdesktop/ytmdesktop#996] opened 2022-07-11 18:44 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Settings menu inside YTMDesktop won't load. I've ran ytmdesktop through terminal and no errors come up as i try to open the settings. It's just stuck on a loading circle. the rest of the app works though.

### Expected Behavior

To be able to edit settings such as Discord RPC.

### Steps To Reproduce

1. Install from the Arch AUR
2. Open the application
3. Press settings cog

### YTMDesktop

1.14.2

### OS

Arch Linux

### OS Version

5.18.10-arch1-1

### Arch

x64

### Installation way

AUR

### Anything else?

DE: KDE Plasma
![image](https://user-images.githubusercontent.com/109104272/178335621-90de9ee5-25d0-40f0-a25d-d10e23b37e2a.png)

**Comment by Alipoodle** [comment] 2022-07-12 07:18
Duplicate of #916

**Closed by Alipoodle** 2022-07-12 07:18 UTC

**Comment by Alipoodle** [comment] 2022-07-12 07:21
The whole app has the issue.
Settings cannot be resized so it never redraws it correctly.
