### ISSUE TITLE
<TITLE HERE>

### ISSUE THREAD

**Issue by danieleljugon** [ytmdesktop/ytmdesktop#1180] opened 2023-10-13 00:04 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Discord status listening

### Solution

i think that u can rewrite the code to put in discord listening instead of playing

**Comment by NovusTheory** [comment] 2023-10-13 00:08
Duplicate of #869

**Closed by NovusTheory** 2023-10-13 00:08 UTC
