### ISSUE TITLE
Checkboxes for adding a song to multiple playlists at once

### ISSUE THREAD

**Issue by christophrus** [ytmdesktop/ytmdesktop#641] opened 2021-02-26 11:35 UTC
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Is your feature request related to a problem? Please describe.**
Would be cool to be able to add a song to multiple playlist at once, like in the original Youtube interface, where they are doing it with checkboxes. This would also fix #600

**Comment by Alipoodle** [comment] 2021-10-12 11:36
Duplicate of #397

**Closed by Alipoodle** 2021-10-12 11:36 UTC
