### ISSUE TITLE
Cant' sign in

### ISSUE THREAD

**Issue by feliksczart** [ytmdesktop/ytmdesktop#623] opened 2021-02-15 08:41 UTC
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [x] I verified that there is no open issue for the same subject.

 **Describe the bug**
Nothing happens when I select my Google account to sign in .

 **To Reproduce**
 1. Go to 'SIGN IN'
 2. Click on 'My google account'
 3. Nothing happens

 **Expected behavior**
Sign in to the app.

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.19041***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by flleeppyy** [comment] 2021-02-15 08:58
I'll check this out in a bit

**Comment by flleeppyy** [comment] 2021-02-15 09:05
Could you possibly record/send screenshots of every step you do that causes this?

**Comment by jerdie** [comment] 2021-02-17 04:36
I'm also stuck
![image](https://user-images.githubusercontent.com/5143814/108156830-5d1aea00-711c-11eb-8900-9dede039532b.png)

To Reproduce
Steps to reproduce the behavior:

1. Click sign in
2. input credetials
3. next is just loading.

Environment:

YTMDesktop version: v1.13.0
OS: opensuse tumbleweed
linux: 5.9.14-1
Installation way: snapcraft

**Comment by kovalbogdan95** [comment] 2021-02-19 09:59
Same for me. Stuck on 2-Step Verification

**Comment by flleeppyy** [comment] 2021-02-19 10:11
Hm, i just tried it, it works just fine on master and development

**Comment by ripperapid** [comment] 2021-02-19 12:59
> Same for me. Stuck on 2-Step Verification

If you wait like five minutes, the verification will likely timeout and you are offered alternative 2fa-verification methods.

**Comment by Alipoodle** [comment] 2024-02-02 12:31
Closing issue due to no longer supportinng YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open this issue if this is still occuring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-02 12:31 UTC
Labels: YTMD V1
