### ISSUE TITLE
The sign in button is not working

### ISSUE THREAD

**Issue by ante4** [ytmdesktop/ytmdesktop#923] opened 2022-03-12 21:53 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When i click on the sign-in button it doesn't respond

### Expected Behavior

I should be able to sign in when I click on the sign-in button

### Steps To Reproduce

1. Goto the top navbar and click on sign-in

### YTMDesktop

v1.2.3

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by JPili** [comment] 2022-03-15 11:01
Same here... It says "This browser or app may not be secure." and won't let me sign in at all.

**Comment by JPili** [comment] 2022-03-15 11:17
One of the replies here: https://github.com/ytmdesktop/ytmdesktop/issues/866 explains how to sign in. If the solution doesn't work the first time, try it a few more times. I had to do it twice before it worked.

**Comment by Alipoodle** [comment] 2022-04-13 19:25
Presuming you are running Version 1.2.3
Ya'll need to update.

Otherwise, this issue should be solved within 1.14 already.

Otherwise this is a dupe of #432

**Closed by Alipoodle** 2022-04-13 19:25 UTC

**Comment by JPili** [comment] 2022-04-13 20:04
Thanks for letting us know!

I’m running 1.13 because the ytmdesktop.app website’s download page has a download link for 1.13 and needs to be updated to 1.14. The app doesn’t seem to be telling me to update to 1.14 either.

**Comment by Alipoodle** [comment] 2022-04-14 06:40
1.14 is a pre-release.
Tbh it should really go into release but there's issues like not being a "Secure" Browser to Google
