### ISSUE TITLE
Support U2F

### ISSUE THREAD

**Issue by rahmnathan** [ytmdesktop/ytmdesktop#181] opened 2020-06-03 15:20 UTC
My Google account is secured with a Yubikey. Currently, this stops me from being able to use this application at all. Other snaps like Firefox and KeepassXC support this functionality, for reference.

Until this is resolved, I don't think I can use this application.

**Comment by rickinbsb** [comment] 2020-06-03 19:25
Hello, thanks for using this app! I'm closing this issue as it is a duplicate of #110 and retitled it to be more  clear

**Closed by rickinbsb** 2020-06-03 19:25 UTC

**Comment by rahmnathan** [comment] 2020-06-03 19:27
Thanks @rickinbsb
