### ISSUE TITLE
song stopping at 2.09 and going at the next song

### ISSUE THREAD

**Issue by GhitescuCaterina** [ytmdesktop/ytmdesktop#1090] opened 2023-02-11 20:37 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I dont know at what songs it happens or if its totally random, but sometime the song will stop at 2.09 (yes, i checked, because it stays for a couple seconds at 2.09) and then the next song starts playing. Its kinda funny, but still annoying.
I promise i checked for this online but i didnt find anything as specific as my bug. 

### Expected Behavior

I expect it to not stop i guess :))). If y'all could fix this i'd be forever grateful. If not, its okay, i can always rewind the song before up to 2.09. Thank you for listening to me though !!!

### Steps To Reproduce

There is not a lot you could do expect put a playlist of 50 songs (more than 2 minutes and 15 seconds long) on repeat and wait until one of them stops and skips to the next song.

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

just, from the online, in not very good with tech stuff im sorry

**Comment by GoldandGore** [comment] 2023-04-12 02:12
I have the same problem and the only way I've been able to subdue the issue is closing and reopening the program everyday. It eats my queue, but the 2:09 issue doesn't reoccur until the next day or two. I also sleep my computer at night if that's a factor. This might be a server issue though because I think it's happened on an official channel I used in the past (can't remember if it was a browser feature, the webpage, or the official Youtube Music program).

**Comment by Alipoodle** [comment] 2024-02-04 17:41
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-04 17:41 UTC
Labels: YTMD V1
