### ISSUE TITLE
can´t log in

### ISSUE THREAD

**Issue by rodrigoromo28** [ytmdesktop/ytmdesktop#985] opened 2022-06-17 18:57 UTC
google says the browser is not secure, so I can´t log in

- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ ] I verified that there is no open issue for the same subject.

 **Describe the bug**

 **To Reproduce**
 3. See error

 **Expected behavior**

 **Screenshots**

 **Environment:**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***win32***
 * OS version: ***10.0.22000***
 * Arch: ***x64***
 * Installation way: ***like .exe or snapcraft or another way***

**Comment by NovusTheory** [comment] 2022-06-17 19:07
Duplicate of #866

**Closed by NovusTheory** 2022-06-17 19:07 UTC
