### ISSUE TITLE
A Javascript Error occurred in the main process when switching to next track

### ISSUE THREAD

**Issue by psiryan** [ytmdesktop/ytmdesktop#734] opened 2021-06-02 18:32 UTC
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [X] I verified that there is no open issue for the same subject.

**Describe the bug**
Error message dialog pops up (sometimes/intermittently) when switching to another track in queue or playlist. Message contents:
```
Uncaught Exception:
Error: Failed to serialize arguments at WebContents._.send (electron/js2c/browser_init.js:-157:2252)
    at: sendMsg (/tmp/.mount_YouTubkiJYnD/resources/app.asar/-node_modules/electron-native-notification/index.js:49:46)
    at: BrowserWindow.<anonymous> (/tmp/.mount_YouTubkiJYnD/-resources/app.asar/node_modules/electron-native-notification/-index.js:55:40)
    at BrowserWindow.emit (events.js:322:22)
```

**To Reproduce**
1. Play music from saved playlist or radio playlist
2. continue listening for indeterminate amount of time
3. See error dialog appear

**Expected behavior**
Music playlist streams continuously without any unexpected popups.

**Screenshots**
![2021-06-02-10-28-47](https://user-images.githubusercontent.com/5029072/120533610-c35b0e00-c395-11eb-80b0-00984995289b.png)

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.13.0***
 * OS: ***Linux***
 * OS version: ***Arch Linux***
 * Arch: ***x64***
* Installation way: ***AppImage***

**Comment by Alipoodle** [comment] 2021-06-02 20:56
This appears to be happening from sending of Notifications by the looks of it. (Notifications won't send if you are viewing the window)

Can you confirm if you continue to get the issue when the Show Notification option is off?
App Settings -> General
![image](https://user-images.githubusercontent.com/17199186/120550271-8bcb8080-c3ec-11eb-95c0-6ffcd4ff90b7.png)
This is only a temporary fix.

Additionally, Do you have the Tray Icon currently Enabled?

**Comment by psiryan** [comment] 2021-06-04 16:38
Tray icon is enabled, yes. I will check and confirm the notification setting as I'm using the app today.

**Comment by Alipoodle** [comment] 2021-10-11 21:38
The master ticket for this is #367.
The issue is fixed in Development build but not in a Public release yet. Please review the other ticket for more information.

**Closed by Alipoodle** 2021-10-11 21:38 UTC
