### ISSUE TITLE
Logging in with 2FA (YubiKey) Does not allow you to authenticate

### ISSUE THREAD

**Issue by CharlesMorgan-IOHK** [ytmdesktop/ytmdesktop#232] opened 2020-07-08 20:39 UTC
#### Environment 
 * YTMDesktop: - 
 * Platform: linux 
![Screenshot from 2020-07-08 16-38-05](https://user-images.githubusercontent.com/15351828/86968098-937d9900-c139-11ea-9fe1-bdf81a54b571.png)

 * Arch: x64 
 * Version: 5.4.0-39-generic 
 * Memory: 126 GB 
 * Node: 12.14.1 
###### (if possible)

**Comment by rickinbsb** [comment] 2020-07-10 01:05
Hello! Thanks for the feedback!
I'm closing this as a duplicate of #110

**Closed by rickinbsb** 2020-07-10 01:05 UTC
