### ISSUE TITLE
ublock integration

### ISSUE THREAD

**Issue by randomstuff69** [ytmdesktop/ytmdesktop#1468] opened 2024-11-13 18:17 UTC
### Consent

- [x] I verified that there is no open/closed issue for the same subject.
- [x] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

ublock origin intergration

### Solution

add the chrome extension ublock origin in it to block ads

### Alternatives

use ublock on browser

**Comment by Alipoodle** [comment] 2024-11-13 18:43
Duplicate of #114

**Closed by Alipoodle** 2024-11-13 18:43 UTC
