### ISSUE TITLE
Mulitmonitor - App opens in phantom window when using different multiscreen setup

### ISSUE THREAD

**Issue by inertia666** [ytmdesktop/ytmdesktop#1040] opened 2022-10-14 06:28 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

I use three screens at the office and had the app open in one of the screens.

When I came home and moved to my two screen setup, I could not see the app when opening it. 

Coming back to the office, the app opens normally in the screen that was missing at my home office.

### Expected Behavior

Should adapt itself and open in an active screen.

### Steps To Reproduce

1. Use more than one screen
2. Move the app to a screen
3. Close the app
4. Change screen configuration so the screen the app was moved to is missing
5. Try to open the app

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by inertia666** [comment] 2022-10-20 08:05
I researched a little further how to reset this problem and it's in the config.json file in the profile folder

"window-position": {
		"x": -1329,
		"y": 95
	}

The app should check if this is a valid window position and reset if not.

**Comment by Alipoodle** [comment] 2023-02-11 20:57
Dupe of #1016

**Closed by Alipoodle** 2023-02-11 20:57 UTC
