### ISSUE TITLE
Mini Player is too wide

### ISSUE THREAD

**Issue by ItsEverest** [ytmdesktop/ytmdesktop#1043] opened 2022-10-22 13:58 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://user-images.githubusercontent.com/78271762/197342912-70e9b915-7caa-4f64-bac3-5aaa760826af.png)
The album windows isn't square, but rectangle.

### Expected Behavior

It should be square, no free spaces, just in the shape of the album/music cover

### Steps To Reproduce

1. Open YTD App
2. Play any song
3. Right click the cover/video
4. Enable miniplayer

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

11

### Arch

x64

### Installation way

.exe

**Comment by Alipoodle** [comment] 2022-10-22 19:04
![image](https://user-images.githubusercontent.com/17199186/197358182-00933d22-6788-448f-801e-bfa5fc960ae3.png)
You're gonna need to provide some more steps to this as just "Enabling it" doesn't do anything.
Does resizing it once fix this issue?

**Comment by NintyS** [comment] 2022-10-27 12:42
I have it too. On Ubuntu 20.04. IDK what are steps to reproduce it, except it you have to use a mini player version.
![image](https://user-images.githubusercontent.com/31569763/198287081-6ac0727e-ecf4-4da6-a9f9-5d1d6108d27c.png)

**Comment by Kirihan** [comment] 2022-10-30 01:52
Just tried miniplayer since i saw it, I just started it and played a song then hit miniplayer button

YTMDesktop
v1.13.0
OS
Windows
OS Version
10
Arch
x64

Installation way
.exe

![image](https://user-images.githubusercontent.com/45792238/198858997-c021ed9b-1545-46b8-8293-5a3df73590bb.png)

**Comment by jwaxy** [comment] 2022-11-14 15:23
I have the same issue on Pop!_OS 22.04. Any fixes?

**Comment by Alipoodle** [comment] 2024-02-05 16:24
Miniplayer has been removed and will be re-worked when re-added. Closing this bug for the time being.

**Closed by Alipoodle** 2024-02-05 16:24 UTC
