### ISSUE TITLE
I LOVE this, and would love to contribute, however...

### ISSUE THREAD

**Issue by TechLionDev** [ytmdesktop/ytmdesktop#1102] opened 2023-03-22 21:20 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I Have an ad-blocker, and I was wondering if it was possible to use with this desktop app, Thanks!

### Solution

N/A

### Alternatives

N/A

### Anything else?

N/A

**Comment by Alipoodle** [comment] 2023-03-22 21:52
Duplicate of #114

**Closed by Alipoodle** 2023-03-22 21:52 UTC
