### ISSUE TITLE
Crash after looping an album

### ISSUE THREAD

**Issue by gordli** [ytmdesktop/ytmdesktop#1292] opened 2024-02-07 21:22 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Crash experienced after looping an album (playing with 'repeat all'), not sure how many times it has been looped.

### Expected Behavior

Didn't have this issue on v2 r5

### Steps To Reproduce

Press play on an album with 'repeat all' enabled

### YTMDesktop

2.0.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

YouTube Music Desktop App Crashed

Environment Details:
    YouTube Music Desktop App 2.0.0
    Electron 28.2.0
    Windows NT 10.0.19045

Name: Error
Message: Unhandled error. ('Command failed: 4294967295\n' +
  'System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '   --- End of inner exception stack trace ---\r\n' +
  '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
  '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
  '   at Squirrel.Update.Program.main(String[] args)\r\n' +
  '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
  '---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
  '\r\n')
Cause: Unknown

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Command failed: 4294967295\n' +
  'System.AggregateException: One or more errors occurred. ---> System.Exception: Remote release File is empty or corrupted\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '   --- End of inner exception stack trace ---\r\n' +
  '   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\r\n' +
  '   at Squirrel.Update.Program.executeCommandLine(String[] args)\r\n' +
  '   at Squirrel.Update.Program.main(String[] args)\r\n' +
  '   at Squirrel.Update.Program.Main(String[] args)\r\n' +
  '---> (Inner Exception #0) System.Exception: Remote release File is empty or corrupted\r\n' +
  '   at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.UpdateManager.<CheckForUpdate>d__8.MoveNext()\r\n' +
  '--- End of stack trace from previous location where exception was thrown ---\r\n' +
  '   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n' +
  '   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n' +
  '   at Squirrel.Update.Program.<CheckForUpdate>d__8.MoveNext()<---\r\n' +
  '\r\n')
    at new NodeError (node:internal/errors:405:5)
    at AutoUpdater.emit (node:events:506:17)
    at AutoUpdater.emitError (node:electron/js2c/browser_init:2:3868)
    at node:electron/js2c/browser_init:2:3444
    at node:electron/js2c/browser_init:2:5035
    at ChildProcess.<anonymous> (node:electron/js2c/browser_init:2:4741)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)

**Comment by NovusTheory** [comment] 2024-02-07 22:27
Duplicate of #1266

(#1266 issue renamed for clarity and closing in favor of)

**Closed by NovusTheory** 2024-02-07 22:27 UTC
