### ISSUE TITLE
[Feature Request] Android notification bar control for running in the background.

### ISSUE THREAD

**Issue by Matakor** [ytmdesktop/ytmdesktop#920] opened 2022-03-07 05:33 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Basically just a notification bar control for the app, similar to how YTM has a notification control setup. This way I can do other things on my phone while controlling the app and doesn't require me to switch the apps.

### Anything else?

![ytm notif bar control example](https://user-images.githubusercontent.com/6760522/156973877-d7d468f1-3ebd-44c3-9818-ae7185224879.jpg)

**Comment by kudlav** [comment] 2022-04-27 05:35
Duplicate of https://github.com/ytmdesktop/ytmdesktop/issues/813

**Closed** 2022-04-27 10:04 UTC
