### ISSUE TITLE
Uncaught exception: Failed to serialize arguments

### ISSUE THREAD

**Issue by vitogoh** [ytmdesktop/ytmdesktop#895] opened 2022-01-27 01:32 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

![image](https://user-images.githubusercontent.com/1999704/151274791-4a4e05e9-8666-46d6-8d69-89d844b9e432.png)

it seems to throw this error when switching to the next track

### Expected Behavior

The app not throwing the javascript error when switching to a new track

### Steps To Reproduce

1. Minimize to tray

### YTMDesktop

v1.13.0

### OS

popOS

### OS Version

21.04

### Arch

x64

### Installation way

x86 Appimage

**Comment by Alipoodle** [comment] 2022-01-27 11:03
Duplicate of #367
This issue is fixed in the 1.14.1 Development build and is coming soon to a Public Release.

**Closed by Alipoodle** 2022-01-27 11:03 UTC
