### ISSUE TITLE
Playlist modal shows up when clicking next song.

### ISSUE THREAD

**Issue by renatocfrancisco** [ytmdesktop/ytmdesktop#997] opened 2022-07-11 22:30 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Everytime i click to the next or the previous song, the "Add to Playlist" modal pops up. 

### Expected Behavior

The window/modal should not appear, since i am not clicking on the option of "Add to Playlist"

### Steps To Reproduce

1. Select a song from an album or playlist.
2. Click next or previous song

### YTMDesktop

v1.14.2

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

https://user-images.githubusercontent.com/56325092/178369032-62161e63-051a-4b09-8c19-042d25188c46.mp4

**Comment by Alipoodle** [comment] 2022-07-12 07:14
Dupe of #937

**Closed** 2022-07-12 07:14 UTC
