### ISSUE TITLE
Ability to change/disable shortcuts

### ISSUE THREAD

**Issue by Razorpudding** [ytmdesktop/ytmdesktop#258] opened 2020-07-16 23:34 UTC
Ctrl + Shift +Space is how you do big jumps in Warframe haha. SO music keeps pausing and unpausing as I parkour around

**Comment by rickinbsb** [comment] 2020-07-20 12:56
custom hotkeys are being worked on and going to be implemented soon! I'll close this a duplicate of #3

**Closed by rickinbsb** 2020-07-20 12:56 UTC
