### ISSUE TITLE
Support youtube musics (new?) native cast ability

### ISSUE THREAD

**Issue by mrdrogdrog** [ytmdesktop/ytmdesktop#881] opened 2021-12-12 12:58 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

Today I noticed a new button in the YouTube-Music UI. A cast button. This button does not trigger a stream of the tab (which has been my latest workaround). It starts the YT Music App on the Chromecast which is also used by the mobile app for casting. So it seems like YT Music is FINALLY able to cast on its own (again).

<img width="622" alt="image" src="https://user-images.githubusercontent.com/6124140/145713146-44b3f5a6-3091-4266-8923-e150abc239d7.png">

### Solution

This button doesn't appear in YTMDesktop. It would be nice if it would work there, too.

### Alternatives

Use YTMusic in chrome instead of YTMDesktop.

### Anything else?

Related to https://github.com/ytmdesktop/ytmdesktop/issues/29. But this issue is not about a NEW chromecast integration, rather about supporting the existing cast ability of YTM.

In Google Play Music Desktop it was enough to enable mdns in my OS. Seems like this is not enough this time.

**Comment by Alipoodle** [comment] 2021-12-12 15:59
Looking through the stuff for it, by default Electron doesn't have (and doesn't look to be adding) Chromecast support to it natively.
Marshall Of Sound (Electron Developer, Helped with this project, and developer of Google Play Music Desktop Player) has developed [GPMDP/electron-chromecast](https://github.com/GPMDP/electron-chromecast) which is a "Basic" implementation of it, however it's 4 years out of date, and was only intended to work with GPM, so some of the APIs maybe missing within the YT Music integration.

I'll look into this soon as it appears to be fully public now which is great! 😎

**Comment by Alipoodle** [comment] 2022-04-10 15:50
Due to the protection of Electron, and the fact that electron-chromecast was intended for GPMDP,
I've been unable to get this to function. 😅

Both myself and Nova have tried and neither have succeeded.
Looking at other projects it appears it's been done from the ground up instead of just using a more native approach, so unlikely to be something added soon.

**Comment by adammpkins** [comment] 2022-05-12 12:50
@Alipoodle Have you tried this library? It shows an example of a pure JS implementation of using the Chromecast from Node/JavaScript (and thus Electron).

**Comment by Alipoodle** [comment] 2022-05-15 20:12
That is a native integration for the Chrome Cast and not trying to implement Cast for a Chrome window for running a predefined app.
To use this Lib it would require us to use a lot more stuff, and this is more intended for a CLI for casting videos than opening a app.

**Comment by adammpkins** [comment] 2023-11-20 22:30
@Alipoodle  I'm having some luck with the chromecast-api node package. A basic implementation looks like this: 

const ChromecastAPI = require('chromecast-api')

server.js
```
const client = new ChromecastAPI();

console.log('Choose chromecast: ');

client.on('device', function (device) {
    console.log(device.friendlyName);
});

process.stdin.on('data', function (data) {
    var input = data.toString().trim();
    console.log('You typed: ' + input);
    client.devices.forEach(function (device) {
        if (device.friendlyName == input) {
            console.log('Found ' + input + '!');
            var mediaURL = 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_1OMB_MP3.mp3';

            device.play(mediaURL, function (err) {
                if (err) {
                    console.error('Error playing media:', err);
                } else {
                    console.log('Playing media on your chromecast');
                }
            });
        }
    });
});

client.on('error', function (err) {
    console.error('Error:', err);
});

console.log('Looking for Chromecasts...');


const express = require('express');
const http = require('http');
const WebSocket = require('ws');
const ChromecastAPI = require('chromecast-api');

const app = express();
const server = http.createServer(app);
const wss = new WebSocket.Server({ server });
const client = new ChromecastAPI();

app.use(express.static('public')); // Serve static files from 'public' folder

let devices = [];

client.on('device', function (device) {
    devices.push(device); // Store the device for later use
});

wss.on('connection', function connection(ws) {
    devices.forEach(device => {
        // Send existing devices to the client
        ws.send(JSON.stringify(device));
    });

    ws.on('message', function incoming(message) {
        const command = JSON.parse(message);

        if (command.action === 'play') {
            const selectedDevice = devices.find(d => d.friendlyName === command.deviceName);
            if (selectedDevice) {
                var mediaURL = 'http://commondatastorage.googleapis.com/gtv-videos-bucket/big_buck_bunny_1080p.mp4';
                selectedDevice.play(mediaURL, function (err) {
                    if (err) {
                        console.error('Error playing media:', err);
                    } else {
                        console.log('Playing media on your chromecast');
                    }
                });
            }
        }
    });
});

server.listen(3000, function listening() {
    console.log('Listening on %d', server.address().port);
});
```

index.html
```
<!DOCTYPE html>
<html>
<head>
    <title>Chromecast Control</title>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const socket = new WebSocket('ws://localhost:3000');
            const devicesDiv = document.getElementById('devices');

            socket.onmessage = function (event) {
                var device = JSON.parse(event.data);
                var deviceElement = document.createElement('div');
                var deviceName = document.createTextNode(device.friendlyName);
                var playButton = document.createElement('button');

                playButton.innerText = 'Play';
                playButton.onclick = function() {
                    socket.send(JSON.stringify({ action: 'play', deviceName: device.friendlyName }));
                };

                deviceElement.appendChild(deviceName);
                deviceElement.appendChild(playButton);
                devicesDiv.appendChild(deviceElement);
            };

            // You can add more client-side logic here
        });
    </script>
</head>
<body>
    <h1>Chromecast Control</h1>
    <div id="devices"></div>
    <!-- Additional UI elements here -->
</body>
</html>
```

**Comment by Alipoodle** [comment] 2024-02-04 18:15
Duplicate of #29

**Closed by Alipoodle** 2024-02-04 18:15 UTC
Labels: Enhancement, Help wanted
