### ISSUE TITLE
Window off screen every time I open the app

### ISSUE THREAD

**Issue by ricprd** [ytmdesktop/ytmdesktop#1244] opened 2024-01-27 15:23 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Whenever I click the shortcut to launch YouTube Music Desktop, it launches off the margin of the screen and I can't even access the title bar to move it. The only way to movei it is to use Win+→ and then move from the title bar from there. But even when fixing it, the app does not save this position for the next time I launch it.

Here is what it looks like on a 1920x1080 monitor:
![2024-01-27 121912](https://github.com/ytmdesktop/ytmdesktop/assets/15620242/ca3d1cc2-1f8c-4a76-9683-8845a0efcac6)

### Expected Behavior

- The app window launching within the screen's boundaries
- The app window to remember its last position when reopening

### Steps To Reproduce

1. Launch YouTube Music Desktop from the taskbar or start menu

### YTMDesktop

v1.13.0

### OS

Windows

### OS Version

10

### Arch

x64

### Installation way

.exe

### Anything else?

I have a two monitor setup.

**Comment by Alipoodle** [comment] 2024-01-29 15:15
Dupe of https://github.com/ytmdesktop/ytmdesktop/issues/918

**Closed by Alipoodle** 2024-01-29 15:15 UTC
Labels: YTMD V1
