### ISSUE TITLE
WebNowPlaying visualizer glitch

### ISSUE THREAD

**Issue by Maxxt0n** [ytmdesktop/ytmdesktop#283] opened 2020-07-31 21:03 UTC
**Describe the bug**
Using rainmeter monstercat visualizer and have webnowplaying integration turned on in settings of the app
Rainmeter pulls the cover art and uses the color of that to change the visualizer colors to match the thumbnail of the video, but it glitches out every 5 seconds and goes back to white color for half a second and then back to normal. Doesn't happen with browser, only with the youtube music desktop program

**Expected behavior**
Doesn't glitch out and color should stay on until song ends

**Screenshots**
https://gyazo.com/093493b09ad4a886d7c5632692d9f76b

**Environment (please complete the following information):**
 * YTMDesktop version: ***1.11.0***
 * OS: ***Windows***
 * OS version: 1909
 * Arch: ***x64***
* Installation way:  .exe

**Comment by adlerluiz** [comment] 2020-08-01 04:24
thanks for reporting, i will fix it

**Comment by tjhrulz** [comment] 2021-05-08 23:57
Since the cause of this has not been fixed yet in this app I have fixed the cause on my end of the WebNowPlaying plugin, so as long as people have version 0.5.0.0 they will not encounter this bug.

However I still strongly encourage you to cache info in the app and only send the info as it changes as that was what caused this in the first place.

**Comment by Alipoodle** [comment] 2024-01-29 10:24
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:24 UTC
Labels: Bug, YTMD V1
