### ISSUE TITLE
Chromecast/Casting Support in 2022

### ISSUE THREAD

**Issue by ZOXSOCKS** [ytmdesktop/ytmdesktop#938] opened 2022-04-09 20:22 UTC
### Consent

- [X] I verified that there is no open issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Feature

I would love for the possibility of chromecast to be revisited. I'm not sure what APIs are available in 2022 but would love to see Chromecast/casting support enabled soon!

Thanks

**Comment by Alipoodle** [comment] 2022-04-10 15:48
Duplicate of #29

**Closed by Alipoodle** 2022-04-10 15:48 UTC
