### ISSUE TITLE
Info on this "this browser might not be secure" etc

### ISSUE THREAD

**Issue by cfsmp3** [ytmdesktop/ytmdesktop#1010] opened 2022-07-27 17:08 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

Feel free to close. I wanted to add this to the wiki FAQ but I can't contribute to it. I saw there's a thread which is close and therefore can't be updated.

Anyway this seems to be the underlying issue:

https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cif-less-secure-app-access-is-on-for-your-account

Now it's not possible anymore to enable "less secure apps" at all, but you can create a password for an app, like this:

1) Visit https://myaccount.google.com/apppasswords
2) Add a new app, select "Other (custom name)" then type YTMdesktop. It will give you a 16 character password.
3) On the app, use your Google email as usual, then use that password instead of the general one. Once you've entered the app specific password it will ask you for the general one (i.e. you need both).

That's it. No need to go over guest mode, use an old version, etc.

### Expected Behavior

Easy login.

### Steps To Reproduce

See above.

### YTMDesktop

Any

### OS

Linux

### OS Version

Ubuntu

### Arch

x64

### Installation way

.app binary

### Anything else?

N/A

**Comment by HokageSQ** [comment] 2022-07-27 22:40
App Passwords can only be used with accounts that have [2-Step Verification] turned on.

**Comment by cfsmp3** [comment] 2022-07-27 23:10
> App Passwords can only be used with accounts that have [2-Step Verification] turned on.

Isn't that all of them by now?

**Comment by Alipoodle** [comment] 2022-07-28 06:13
Duplicate of #866
There's a few guides at the bottom of the contents to do this without the need of enabling this setting etc.

**Closed by Alipoodle** 2022-07-28 06:13 UTC

**Comment by Alipoodle** [comment] 2022-07-28 06:14
I will later add this to the issue + to FAQ (although most people don't read them unfortunately)
