### ISSUE TITLE
Very high CPU usage even while not playing anything

### ISSUE THREAD

**Issue by rzfzr** [ytmdesktop/ytmdesktop#359] opened 2020-09-01 16:12 UTC
- [ x ] I understand that **YTMDesktop have NO affiliation with Google or YouTube**.
- [ x ] I verified that there is no open issue for the same subject.

**Describe the bug**
CPU usage is high when playing music (just audio from my own uploads, so no video or ads) 15-25% spiking to 30%, my pc is old but not this slow yet... something is off, especially because:
when NOT playing music it keeps using 10-15%

for comparison on edge (base chromium) uses 3-9% CPU while playing and 0-1.5 while stopped...

Computer is the following:
W530 i7 3740QM@3.9Ghz all cores, set for best performance in windows, plugged in
24gb ram, mx500 ssd, quadro k1000m

**Expected behavior**
Use the same amount of CPU as the browser o possibly less, seen it has less overhead

**Environment (please complete the following information):**
 * YTMDesktop version: ***v1.12.1 and v1.13.0-RC2***
 * OS: ***Windows***
 * OS version: ***10 latest***
 * Arch: ***x64*** 
* Installation way: ***.exe***

**Comment by adlerluiz** [comment] 2020-09-03 23:11
thanks for reporting, security and performance improvements are being made

**Comment by rzfzr** [comment] 2020-09-04 03:20
great stuff, looks promising, needing any logs I'll provide them.
happy coding

**Comment by shyim** [comment] 2020-09-12 19:34
![image](https://user-images.githubusercontent.com/6224096/93003520-b5cbd280-f53f-11ea-9280-c265e985c90a.png)

Should I Creat efor this an own issue?

**Comment by tuomas2** [comment] 2020-09-23 08:05
Same here, v1.13.0, linux (installed via snap). My laptop hardware is rather powerful but still fan is very loud all the time.

**Comment by iacosta3994** [comment] 2020-09-23 23:17
I've been having issues when the program is in the background and no music is playing. I have an RTX 2070 but it takes up more than 10% of the GPU to run idle. CPU load is pretty load but I'm unsure what it's running in the background. 
![image](https://user-images.githubusercontent.com/46463653/94083498-284a7700-fdb8-11ea-9fd6-d8ffdfd35dea.png)

**Comment by rzfzr** [comment] 2020-09-24 10:44
> I have an RTX 2070 but it takes up more than 10% of the GPU to run idle.
>... but I'm unsure what it's running in the background for the GPU.

Maybe it's mining a little tiny bitcoin 😉
just joking ofc

**Comment by shyim** [comment] 2020-09-24 11:06
I guess the Issue is Youtube Music itself and not the repository here. In Browser it's laggy too

**Comment by rzfzr** [comment] 2020-09-24 11:25
> I guess the Issue is Youtube Music itself and not the repository here. In Browser it's laggy too

YM is definitely not perfect, opened in the browser after a few days it is consuming a huge amount of ram, and I have to close it and open it again to clear it...
But in normal use at least in my system this app uses way more resource even when not playing

**Comment by iacosta3994** [comment] 2020-09-24 21:55
> > I have an RTX 2070 but it takes up more than 10% of the GPU to run idle.
> > ... but I'm unsure what it's running in the background for the GPU.
> 
> Maybe it's mining a little tiny bitcoin 😉
> just joking ofc

Haha, that was my first thought, that's why I came to git hub and looked at the source code to see if that is why it's runny my GPU  higher than expected. Then I saw that it was already an open issue.

**Comment by cuquiwi** [comment] 2020-09-25 09:16
![image](https://user-images.githubusercontent.com/2592637/94248907-6f9f4780-ff1f-11ea-83a4-90f89b2b122b.png)

I don't know if this might help, those are my processes running that take most of the CPU when there is no music playing.
Even if it's in linux I still have the same problem.
Does anybody has the same problem with another electron based application?

**Comment by Block81838** [comment] 2020-10-03 05:16
I got this problem too, it's so lag, hog down my pc

**Comment by ignas04-2** [comment] 2020-10-21 19:46
Using 30% of my GPU, Nvidia RTX 2060. Been using this for a few weeks, only been like this today (this morning it was fine though).

**Comment by fortris** [comment] 2020-12-04 08:31
Also a problem for me, while idle I can see up to 12% CPU usage on a 5 GHz 7700k and 6% GPU usage on a 3090 which is worrying. While YouTube music is open in a chrome tab it's only managed to use 4% CPU at most.

**Comment by IndefiniteBen** [comment] 2021-01-16 18:05
Any update on these performance improvements @adlerluiz ?

**Comment by quantum13** [comment] 2021-01-28 03:42
v1.13.0, ubuntu, appimage, i7, 32gb ram
on the first screenshot cpu consumption of just run app, without music playing
several consecutive calls of top to show dynamic of consumption
![image](https://user-images.githubusercontent.com/1215671/106086133-9cb07080-6132-11eb-8cb3-6947ea2974f8.png)

on the second - playing radio on playlist, >50% cpu load
![image](https://user-images.githubusercontent.com/1215671/106086404-22342080-6133-11eb-92a4-c8fa67cfc314.png)
--
on the next screenshots consumption on browser vivaldi (chrome based, just separate browser to run ym only)
without any tabs opened
![image](https://user-images.githubusercontent.com/1215671/106086630-953d9700-6133-11eb-995b-734fe67f36fc.png)

opened ym music main page without playing music
![image](https://user-images.githubusercontent.com/1215671/106086705-bef6be00-6133-11eb-9b28-de278834077b.png)

playing radio on playlist, 35% cpu load in peak
![image](https://user-images.githubusercontent.com/1215671/106086837-f49ba700-6133-11eb-9c2b-7a8cdcb31005.png)

**Comment by eaigner** [comment] 2021-01-31 09:01
A few helper processes are always at ~10% even in idle.

![Screen Shot 2021-01-31 at 10 01 01](https://user-images.githubusercontent.com/112197/106379299-3c783380-63ab-11eb-80cf-973a9e1dfc9d.png)

**Comment by Mizumaky** [comment] 2021-02-15 14:50
Same here - takes up between 3-10% when idle, even when the window is closed. The only thing it should be doing is to listen for keyboard input or system tray action and keep the session in memory to be available to continue playing, but there is obviously something more to it. I see this as a major problem, since I usually run multiple apps at once and my laptop's two-core i7 starts to struggle with that quite often, so having a constant ~6% hugged is really no good.

**Comment by norabelrose** [comment] 2021-02-21 23:49
Same problem here on Ubuntu 20.10. I noticed that the app is causing my fan to turn on even when I'm not listening to music and I'm just doing light text editing. It seems like it should be pretty straightforward to profile the app and figure out what is actually using up so much CPU- I will try to do this myself when I have some free time.

**Comment by skipfie** [comment] 2021-03-06 04:07
![image](https://user-images.githubusercontent.com/20710759/110194654-29171880-7dee-11eb-9c0a-387b7f18cc9d.png)
Seeing the same issue on Windows 10 20H2 19042.804

**Comment by kennykingdev** [comment] 2021-03-29 23:40
Same issue on Arch Linux, installed through AUR.

My guess is that the issue is somewhere in the rendering of the app.  Which matches with the screenshot from @skipfie where the display went blank when the process was killed.

htop (filtered on 'ytmdesktop') shows more info on the processes that are using up the CPU.  These two screenshots are typical numbers I'm seeing. Music is playing both times.

This is with the window open:
![Screenshot_20210329_163217](https://user-images.githubusercontent.com/16931002/112912444-677dbb80-90ac-11eb-9fde-fa46628430ee.png)

This is with the window minimized:
![Screenshot_20210329_163235](https://user-images.githubusercontent.com/16931002/112912456-6c426f80-90ac-11eb-921b-880239895fc9.png)

Both process using up the most CPU when the window is up show commands with --type=renderer.  I can provide more info from the commands using the processor most if it would help, but it's about 3 screens wide on my 1440p monitor

**Comment by alexgmin** [comment] 2021-03-30 14:27
Can reproduce previous message. App uses a lot less cpu when it's minimized on my Ubuntu 20.10.

**Comment by mkapln2** [comment] 2021-04-07 09:18
I am having same problem at Version 1.13.0 
Minimal cpu usage is %15 even i dont listen music 
![image](https://user-images.githubusercontent.com/33043062/113842048-fd939f00-979a-11eb-9aaa-cb5ee6adc28f.png)


I hope it would be solved soon

**Comment by Hegom** [comment] 2021-06-11 23:46
Just run some benchmarks, ytmdesktop decreases by about 10% the GPU performance, this a serious issue.

**Comment by mark-pictor-csec** [comment] 2022-04-15 17:02
I've seen relatively high cpu usage from it, though not as bad as others are reporting. What I did notice, via `iosnoop` (osx), is that it re-reads a certain file multiple times a second. Been a while, but I think it was a config file.

Not sure what the iosnoop equivalent on windows would be; on linux you could do something like `strace -e file -o ytmd.str -p <ytmd main pid> -f`. Let it run for 30s or so, then ctrl-c. The file should show all file operations ytmd or subprocesses performed.

**Comment by dominiklenne** [comment] 2022-09-16 11:09
on w10 dell 6520  8 - 10% cpu load without playing , 12% when playing music.
i like the app but it lets my fan run all the time...

**Comment by M2ast** [comment] 2022-10-19 18:24
Very high RAM usage and CPU without any music playing. NO reason this should be using 6 gigs of RAM.

![ytdesktop](https://user-images.githubusercontent.com/102571259/196773716-bb9c6460-1e1f-4562-ad64-ce3389ed5702.png)

**Comment by mingjun97** [comment] 2022-10-19 20:49
> 

This seems a ytm issue. Play music in the browser for a long time will have the same behavior.

**Comment by M2ast** [comment] 2022-10-19 20:56
> > 
> 
> This seems a ytm issue. Play music in the browser for a long time will have the same behavior.

This happens when I'm not playing _any_ music. The app just hogs RAM and CPU while sitting in the system tray.

**Comment by mingjun97** [comment] 2022-10-19 20:59
> > > 
> > 
> > 
> > This seems a ytm issue. Play music in the browser for a long time will have the same behavior.
> 
> This happens when I'm not playing _any_ music. The app just hogs RAM and CPU while sitting in the system tray.

Yes. YTM has memory leakage issue irrc. This usually happens after a long time of playing music no matter currently idle or not.

**Comment by M2ast** [comment] 2022-10-19 23:40
We're over 2 years now on this open issue, are we just accepting that YTMD will continue to enable this leakage? Why haven't we coded in an application restart once mem usage gets to a certain point?

**Comment by Hi-Angel** [comment] 2022-10-23 16:23
Note that the problem persists in Chrome on music.youtube site as well. So I did some research and found:

1. In Chrome the problem may be worked around by running with `--no-sandbox` command line argument. 
2. For Firefox I didn't manage to find a workaround simply because it's sporadic there, and at some point it stopped reproducing for me.

Some observations that hopefully may be useful:

* `--no-sandbox` fixes it for Chrome
* The problem may happen in both Chrome and Firefox, however on Firefox it happens sporadically, whereas in Chrome it's always reproducible
    * in Firefox the problem may appear at first, but then go away. From what I've seen it never reappeared again unless I restarted Firefox. Closing/Opening the tab in particular never made it start reproducing again for me.
* Problem never appears in Chrome nor Firefox if you are logged out. IOW it is only reproducible when you're logged-in.
* CPU usage is a little bit higher in Chrome *(≈22%)*, than it is in Firefox *(≈16)*
* In both browsers the process has lots of threads — graphics stuff, audio, media… However, the CPU is always being taken by the main thread whose TID is equal to the PID.
* it's caused by various timeouts
  * Chrome repeatedly calls a `futex()` and gets a "Connection timed out"
  * Firefox repeatedly calls a `poll()` on read-side of a pipe, but receives TIMEOUT

**Comment by Jeremy-Freeman** [comment] 2022-11-02 17:55
Another thing I've noticed -- using YMD, if you switch to the Miniplayer, CPU usage goes down by half! 🤔

**Comment by crzsotona** [comment] 2022-11-10 20:46
What's the point in using this app if I can open another browser window or profile?
BTW does anyone tried to open YTM in Ferdi? )

**Comment by Alipoodle** [comment] 2024-01-29 10:24
Closing this PR in the move to YTMD v2

**Closed by Alipoodle** 2024-01-29 10:24 UTC
Labels: Performance, YTMD V1
