### ISSUE TITLE
Bug: App is not sending album/album artist to Last.fm

### ISSUE THREAD

**Issue by festivefirstname** [ytmdesktop/ytmdesktop#120] opened 2020-03-21 17:44 UTC
I noticed that a track I had listened to this week on my phone with YTM + Scroball app, and GPM desktop player on another device, was being scrobbled differently when I tried out this YTM desktop player. I have a last.fm subscription so I can go in and edit scrobbled metadata and found that the tracks from from YTM desktop were missing album and album artist data. Can that be enabled in the next update? I edited those scrobbles already but can do it again for an example if needed!

**Comment by restinginlove** [comment] 2020-05-25 16:54
Seeing as this is closed, will this not be fixed then, @adlerluiz? :( Just now reinstalled from https://ytmdesktop.app/ to make sure I have the latest and tested, and it's still not registering albums + album artists and populating album versions when it should be single, and other errors. Guess I'll continue to roll with the web scrobbler and the official youtube music PWA so my scrobble history is accurate...

**Comment by rickinbsb** [comment] 2020-05-26 21:42
hi @restinginlove, I believe closing this was an accident, but this should be implemented on 1.10

**Comment by adlerluiz** [comment] 2020-05-26 23:21
sorry for the inconvenience, I really made the correction and added the album in the scrobbler option but I found out that the library I use for that, does not support album scrobble and there is a pending PR that was never accepted, I am considering making a fork and accepting this PR or manually implement scrobble for Last.FM

https://github.com/TerrordactylDesigns/scribble/pull/5

**Comment by rickinbsb** [comment] 2020-06-01 23:20
I'm repurposing this issue as a bugfix instead of a new feature for now

**Comment by AquaMorph** [comment] 2020-09-18 18:47
I did some digging and the reason why album information is not being sent to Last.fm is the scribble npm module is very limited and does not support scrobbling album info. Also the module has not been updated in 6 years and the developer has not done anything on GitHub in 5 years. It would probably be best to switchout the library used for scobbling with something better.

**Comment by aquinox77** [comment] 2021-02-19 16:38
> I did some digging and the reason why album information is not being sent to Last.fm is the scribble npm module is very limited and does not support scrobbling album info. Also the module has not been updated in 6 years and the developer has not done anything on GitHub in 5 years. It would probably be best to switchout the library used for scobbling with something better.

Bumping this. When you say "switch out the library used for ... something better", do you mean just not using last.fm to scrobble? I'm new to this, but also experiencing that album art issue.

**Comment by AquaMorph** [comment] 2021-02-19 18:04
> Bumping this. When you say "switch out the library used for ... something better", do you mean just not using last.fm to scrobble? I'm new to this, but also experiencing that album art issue.
This program uses a module that is a wrapper for the last.fm API. Basically this makes it easier to send and receive information from last.fm. Anyone can create one to interface with last.fm. The problem is the one that was chosen isn't featured complete and is not being updated. It's not capable of sending album information so another module needs to be chosen and the code of this program updated to use it or a custom implementation of the last.fm API needs to written.

**Comment by Alipoodle** [comment] 2024-02-04 17:47
Closing issue due to no longer supporting YouTube Music Desktop v1 + Release of YouTube Music v2.
Please re-open a NEW issue if this is still occurring in the latest build of the application, however as a re-write has been done on the entire project most issues will be fixed, no longer a feature or re-worked.

**Closed by Alipoodle** 2024-02-04 17:47 UTC
Labels: Bug
