### ISSUE TITLE
Settings menu and mini-player stuck on loading screen

### ISSUE THREAD

**Issue by Fosserus** [ytmdesktop/ytmdesktop#1008] opened 2022-07-21 03:17 UTC
### Consent

- [X] I verified that there is no open/closed issue for the same subject.
- [X] I understand that **YTMDesktop have NO affiliation with Google or YouTube**

### Current Behavior

When I go to the settings menu, a new window opens as expected; but nothing loads in. It's stuck on the loading screen.

### Expected Behavior

I expected the window to load and show the settings menu.

### Steps To Reproduce

1. Download the latest release from the Github repo and install it.
2. Open up the program and click the "Settings" cog wheel.

### YTMDesktop

v1.14.2

### OS

Linux

### OS Version

Arch

### Arch

x64

### Installation way

Cloning the aur repository link for (ytmdesktop-git) and making the package (makepkg -si)

### Anything else?

The link that I used to clone the installer for the app: https://aur.archlinux.org/ytmdesktop-git.git

**Comment by Alipoodle** [comment] 2022-07-21 18:45
Duplicate of #916

**Closed by Alipoodle** 2022-07-21 18:45 UTC
